--Balloonshroom Q
local scard,sid=aux.GetID()
function scard.initial_effect(c)
	aux.AddRace(c,RACE_SURVIVOR,RACE_BALLOON_MUSHROOM)
	--creature
	aux.EnableCreatureAttribute(c)
	--survivor (destroy replace - to mana zone)
	aux.AddSingleReplaceEffectDestroy(c,0,scard.tg1,scard.op1)
	local e1=Effect.CreateEffect(c)
	e1:SetDescription(aux.Stringid(sid,0))
	e1:SetType(EFFECT_TYPE_SINGLE+EFFECT_TYPE_CONTINUOUS)
	e1:SetCode(EFFECT_DESTROY_REPLACE)
	e1:SetProperty(EFFECT_FLAG_SINGLE_RANGE)
	e1:SetRange(LOCATION_BZONE)
	e1:SetTarget(scard.tg1)
	e1:SetOperation(scard.op1)
	local e2=Effect.CreateEffect(c)
	e2:SetType(EFFECT_TYPE_FIELD+EFFECT_TYPE_GRANT)
	e2:SetRange(LOCATION_BZONE)
	e2:SetTargetRange(LOCATION_ALL,0)
	e2:SetTarget(aux.TargetBoolFunctionExceptSelf(Card.DMIsRace,RACE_SURVIVOR))
	e2:SetLabelObject(e1)
	c:RegisterEffect(e2)
end
--survivor (destroy replace - to mana zone)
scard.tg1=aux.SingleReplaceDestroyTarget(Card.IsAbleToMZone)
function scard.op1(e,tp,eg,ep,ev,re,r,rp)
	local c=e:GetHandler()
	Duel.Hint(HINT_CARD,0,c:GetOriginalCode())
	Duel.Hint(HINT_OPSELECTED,1-tp,e:GetDescription())
	Duel.SendtoMZone(c,POS_FACEUP_UNTAPPED,REASON_EFFECT+REASON_REPLACE)
end
