--Min/Max Value
MIN_ID			=1000		--4 digit, by DataManager::GetDesc()
MAX_ID			=268435455	--9 digit, by DataManager::GetDesc()
MAX_COUNTER		=65535		--max number for adding/removing counters, by card::add_counter(), field::remove_counter()
MAX_NUMBER		=999999999	--Max number allowed in YGOPro
MAX_MANA_COST	=4294967295	--"Dormageddon X, Forbidden Armageddon" (DMR-23 FFL1,FFL2,FFL3,FFL4,FFL5/FFL5)
--Card ID
CARD_WOLFIS_BLUE_DIVINE_DRAGON	=10027		--EVENT_CUSTOM+EVENT_BECOME_SHIELD_TRIGGER
CARD_HOLY_AWE					=10001006	--EVENT_CUSTOM+EVENT_TRIGGER_SHIELD_TRIGGER
CARD_BLOODY_SQUITO				=10001046	--EVENT_CUSTOM+EVENT_WIN_BATTLE
CARD_CREEPING_PLAGUE			=10001049	--EVENT_CUSTOM+EVENT_BECOME_BLOCKED
CARD_SPIRAL_GRASS				=10002010	--EVENT_CUSTOM+EVENT_BLOCK
CARD_MARROW_OOZE_THE_TWISTER	=10002032	--EVENT_CUSTOM+EVENT_ATTACK_PLAYER
CARD_BRUTAL_CHARGE				=10005049	--EVENT_CUSTOM+EVENT_BREAK_SHIELD
CARD_KACHUA_KEEPER				=10008005	--EVENT_CUSTOM+EVENT_EVOLUTION_TO_BZONE
CARD_STORM_WRANGLER_THE_FURIOUS	=10009051	--EVENT_CUSTOM+EVENT_TRIGGER_BLOCKER
CARD_BLUUM_ERKIS_FLARE_GUARDIAN	=10010119	--EVENT_CUSTOM+EVENT_CAST_FREE
CARD_WARPED_LUNATRON			=10011023	--EVENT_CUSTOM+EVENT_UNTAP_START_STEP
CARD_SOUL_PHOENIX				=10012005	--EVENT_CUSTOM+EVENT_TO_SZONE
CARD_GASHI_GASHI				=10013034	--EVENT_CUSTOM+EVENT_LOSE_BATTLE
--Location
LOCATION_ALL		=0xff		--All locations
LOCATION_DECK		=0x01		--Deck
LOCATION_HAND		=0x02		--Hand
LOCATION_BZONE		=0x04		--Battle Zone
LOCATION_SZONE		=0x08		--Shield Zone (sequences 0~4)
LOCATION_MZONEUNT	=0x10		--Mana Zone (untapped cards)
LOCATION_MZONETAP	=0x20		--Mana Zone (tapped cards)
LOCATION_GRAVE		=0x20		--Graveyard
LOCATION_MZONE		=0x30		--Mana Zone
LOCATION_EXTRA		=0x40		--(unused)
LOCATION_ESOURCE	=0x80		--Evolution Source
--Location (for redirect)
--If you specify LOCATION_DECK in the redirection effect, the card will return to the top of the deck
LOCATION_DECKBOT	=0x10001	--(unused)
LOCATION_DECKSHF	=0x20001	--(unused)
--Deck Sequence (for Duel.SendtoDeck)
SEQ_DECK_TOP		=0		--Return to the top of the deck
SEQ_DECK_BOTTOM		=1		--Return to the bottom of the deck
SEQ_DECK_SHUFFLE	=2		--Shuffle into the deck
SEQ_DECK_UNEXIST	=-2		--Disappear from the game
--Zone Sequence (for Card.GetSequence, Card.GetPreviousSequence, etc.)
SEQ_MZONE_LEFT		=0		--(reserved) Leftmost Main Monster Zone
SEQ_MZONE_MID_LEFT	=1		--(reserved) Center-left Main Monster Zone
SEQ_MZONE_MID		=2		--(reserved) Center Main Monster Zone
SEQ_MZONE_MID_RIGHT	=3		--(reserved) Center-right Main Monster Zone
SEQ_MZONE_RIGHT		=4		--(reserved) Rightmost Main Monster Zone
SEQ_MZONE_EX_LEFT	=5		--(reserved) Extra Monster Zone
SEQ_SZONE_LEFT		=0		--(reserved) Leftmost Spell & Trap Zone
SEQ_SZONE_MID_LEFT	=1		--(reserved) Center-left Spell & Trap Zone
SEQ_SZONE_MID		=2		--(reserved) Center Spell & Trap Zone
SEQ_SZONE_MID_RIGHT	=3		--(reserved) Center-right Spell & Trap Zone
SEQ_SZONE_RIGHT		=4		--(reserved) Rightmost Spell & Trap Zone
SEQ_FZONE			=5		--(reserved) Field Zone
--Zone (Location + Sequence, can be used for EFFECT_DISABLE_FIELD)
ZONE_MZONE				=0x7f		--zone=ZONE_MZONE in Duel.SpecialSummon(targets, sumtype, sumplayer, target_player, nocheck, nolimit, pos, zone)
--Position
POS_FACEUP_UNTAPPED		=0x1	--Face-up untapped
POS_FACEDOWN_UNTAPPED	=0x2	--(unused) Face-down untapped
POS_FACEUP_TAPPED		=0x4	--Face-up tapped
POS_FACEDOWN_TAPPED		=0x8	--(unused) Face-down tapped
POS_FACEUP				=0x5	--Face-up
POS_FACEDOWN			=0xa	--Face-down
POS_UNTAPPED			=0x3	--(unused) Untapped
POS_TAPPED				=0xc	--(unused) Tapped
--Card Type
TYPE_MONSTER		=0x1		--(unused)
TYPE_SPELL			=0x2		--Spell
TYPE_TRAP			=0x4		--(unused)
TYPE_NORMAL			=0x10		--(unused)
TYPE_CREATURE		=0x20		--Creature
TYPE_FUSION			=0x40		--(unused)
TYPE_RITUAL			=0x80		--(unused)
TYPE_TRAPMONSTER	=0x100		--(unused)
TYPE_SPIRIT			=0x200		--(unused)
TYPE_UNION			=0x400		--(unused)
TYPE_MULTICOLORED	=0x800		--Card that has 2 or more civilizations
TYPE_NO_ABILITY		=0x1000		--Creature that has no abilities
TYPE_SYNCHRO		=0x2000		--(unused)
TYPE_TOKEN			=0x4000		--(unused)
TYPE_QUICKPLAY		=0x10000	--(unused)
TYPE_CONTINUOUS		=0x20000	--(unused)
TYPE_EQUIP			=0x40000	--(unused)
TYPE_FIELD			=0x80000	--(unused)
TYPE_COUNTER		=0x100000	--(unused)
TYPE_FLIP			=0x200000	--(unused)
TYPE_TOON			=0x400000	--(unused)
TYPE_XYZ			=0x800000	--(unused)
TYPE_PENDULUM		=0x1000000	--(unused)
TYPE_EVOLUTION		=0x2000000	--Evolution creature
TYPE_LINK			=0x4000000	--(unused)
--Civilization
CIVILIZATION_NONE		=0x0	--No civilization (including Zero and Jokers)
CIVILIZATION_ALL		=0x1f	--All civilizations
CIVILIZATION_LIGHT		=0x01	--Light
CIVILIZATION_WATER		=0x02	--Water
CIVILIZATION_DARKNESS	=0x04	--Darkness
CIVILIZATION_FIRE		=0x08	--Fire
CIVILIZATION_NATURE		=0x10	--Nature
CIVILIZATION_COUNT		=5		--Number of different civilizations
--2 color civilization combinations
CIVILIZATIONS_LW		=0x03	--CIVILIZATION_LIGHT+CIVILIZATION_WATER
CIVILIZATIONS_LD		=0x05	--CIVILIZATION_LIGHT+CIVILIZATION_DARKNESS
CIVILIZATIONS_WD		=0x06	--CIVILIZATION_WATER+CIVILIZATION_DARKNESS
CIVILIZATIONS_LF		=0x09	--CIVILIZATION_LIGHT+CIVILIZATION_FIRE
CIVILIZATIONS_WF		=0x0a	--CIVILIZATION_WATER+CIVILIZATION_FIRE
CIVILIZATIONS_DF		=0x0c	--CIVILIZATION_DARKNESS+CIVILIZATION_FIRE
CIVILIZATIONS_LN		=0x11	--CIVILIZATION_LIGHT+CIVILIZATION_NATURE
CIVILIZATIONS_WN		=0x12	--CIVILIZATION_WATER+CIVILIZATION_NATURE
CIVILIZATIONS_DN		=0x14	--CIVILIZATION_DARKNESS+CIVILIZATION_NATURE
CIVILIZATIONS_FN		=0x18	--CIVILIZATION_FIRE+CIVILIZATION_NATURE
--3 color civilization combinations
CIVILIZATIONS_LWD		=0x07	--CIVILIZATIONS_LW+CIVILIZATION_DARKNESS
CIVILIZATIONS_LWF		=0x0b	--CIVILIZATIONS_LW+CIVILIZATION_FIRE
CIVILIZATIONS_LDF		=0x0d	--CIVILIZATIONS_LD+CIVILIZATION_FIRE
CIVILIZATIONS_WDF		=0x0e	--CIVILIZATIONS_WD+CIVILIZATION_FIRE
CIVILIZATIONS_LWN		=0x13	--CIVILIZATIONS_LW+CIVILIZATION_NATURE
CIVILIZATIONS_LDN		=0x15	--CIVILIZATIONS_LD+CIVILIZATION_NATURE
CIVILIZATIONS_WDN		=0x16	--CIVILIZATIONS_WD+CIVILIZATION_NATURE
CIVILIZATIONS_LFN		=0x19	--CIVILIZATIONS_LF+CIVILIZATION_NATURE
CIVILIZATIONS_WFN		=0x1a	--CIVILIZATIONS_WF+CIVILIZATION_NATURE
CIVILIZATIONS_DFN		=0x1c	--CIVILIZATIONS_DF+CIVILIZATION_NATURE
--4 color civilization combinations
CIVILIZATIONS_LWDF		=0x0f	--CIVILIZATIONS_LWD+CIVILIZATION_FIRE
--5 color civilization combinations
CIVILIZATIONS_LWDFN		=0x1f	--CIVILIZATIONS_LWDF+CIVILIZATION_NATURE
--Race (0x1-0x7ff)
RACE_LIGHT_BRINGER		=0x1	--Introduced by "Chilias, the Oracle" (DM-01 1/110)
RACE_GUARDIAN			=0x2	--Introduced by "Dia Nork, Moonlight Guardian" (DM-01 2/110)
RACE_STARLIGHT_TREE		=0x3	--Introduced by "Emerald Grass" (DM-01 3/110)
RACE_INITIATE			=0x4	--Introduced by "Frei, Vizier of Air" (DM-01 4/110)
RACE_BERSERKER			=0x5	--Introduced by "Lah, Purification Enforcer" (DM-01 10/110)
RACE_LIQUID_PEOPLE		=0x6	--Introduced by "Aqua Hulcus" (DM-01 23/110)
RACE_CYBER_VIRUS		=0x7	--Introduced by "Candy Drop" (DM-01 28/110)
RACE_FISH				=0x8	--Introduced by "Hunter Fish" (DM-01 31/110)
RACE_GEL_FISH			=0x9	--Introduced by "Illusionary Merfolk" (DM-01 32/110)
RACE_LEVIATHAN			=0xa	--Introduced by "King Coral" (DM-01 33/110)
RACE_CYBER_LORD			=0xb	--Introduced by "Tropico" (DM-01 42/110)
RACE_GHOST				=0xc	--Introduced by "Black Feather, Shadow of Rage" (DM-01 45/110)
RACE_BRAIN_JACKER		=0xd	--Introduced by "Bloody Squito" (DM-01 46/110)
RACE_LIVING_DEAD		=0xe	--Introduced by "Bone Assassin, the Ripper" (DM-01 47/110)
RACE_CHIMERA			=0xf	--Introduced by "Gigaberos" (DM-01 55/110)
RACE_PARASITE_WORM		=0x10	--Introduced by "Stinger Worm" (DM-01 61/110)
RACE_DARK_LORD			=0x11	--Introduced by "Vampire Silphy" (DM-01 64/110)
RACE_ARMORLOID			=0x12	--Introduced by "Armored Walker Urherion" (DM-01 67/110)
RACE_MACHINE_EATER		=0x13	--Introduced by "Artisan Picora" (DM-01 68/110)
RACE_ARMORED_DRAGON		=0x14	--Introduced by "Bolshack Dragon" (DM-01 69/110)
RACE_HUMAN				=0x15	--Introduced by "Brawler Zyler" (DM-01 70/110)
RACE_DRAGO_NOID			=0x16	--Introduced by "Deadly Fighter Braid Claw" (DM-01 74/110)
RACE_ARMORED_WYVERN		=0x17	--Introduced by "Draglide" (DM-01 75/110)
RACE_ROCK_BEAST			=0x18	--Introduced by "Meteosaur" (DM-01 82/110)
RACE_BEAST_FOLK			=0x19	--Introduced by "Bronze-Arm Tribe" (DM-01 90/110)
RACE_TREE_FOLK			=0x1a	--Introduced by "Coiling Vines" (DM-01 92/110)
RACE_COLONY_BEETLE		=0x1b	--Introduced by "Dome Shell" (DM-01 94/110)
RACE_GIANT_INSECT		=0x1c	--Introduced by "Forest Hornet" (DM-01 96/110)
RACE_BALLOON_MUSHROOM	=0x1d	--Introduced by "Poisonous Mushroom" (DM-01 102/110)
RACE_HORNED_BEAST		=0x1e	--Introduced by "Stampeding Longhorn" (DM-01 104/110)
RACE_ANGEL_COMMAND		=0x1f	--Introduced by "Hanusa, Radiance Elemental" (DM-01 S1/S10)
RACE_DEMON_COMMAND		=0x20	--Introduced by "Deathliger, Lion of Chaos" (DM-01 S5/S10)
RACE_MECHA_THUNDER		=0x21	--Introduced by "Ra Vu, Seeker of Lightning" (DM-03 6/55)
RACE_CYBER_CLUSTER		=0x22	--Introduced by "Angler Cluster" (DM-03 12/55)
RACE_HEDRIAN			=0x23	--Introduced by "Mudman" (DM-03 30/55)
RACE_FIRE_BIRD			=0x24	--Introduced by "Baby Zoppe" (DM-03 35/55)
RACE_GIANT				=0x25	--Introduced by "Dawn Giant" (DM-03 46/55)
RACE_SURVIVOR			=0x26	--Introduced by "Bladerush Skyterror Q" (DM-05 4/55)
RACE_SEA_HACKER			=0x27	--Introduced by "Aeropica" (DM-06 3/110)
RACE_RAINBOW_PHANTOM	=0x28	--Introduced by "Cosmogold, Spectral Knight" (DM-06 17/110)
RACE_GLADIATOR			=0x29	--Introduced by "Telitol, the Explorer" (DM-06 28/110)
RACE_EARTH_EATER		=0x2a	--Introduced by "Hazard Crawler" (DM-06 34/110)
RACE_DEVIL_MASK			=0x2b	--Introduced by "Grinning Axe, the Monstrosity" (DM-06 60/110)
RACE_DEATH_PUPPET		=0x2c	--Introduced by "Junkatz, Rabid Doll" (DM-06 62/110)
RACE_DUNE_GECKO			=0x2d	--Introduced by "Badlands Lizard" (DM-06 74/110)
RACE_XENOPARTS			=0x2e	--Introduced by "Picora's Wrench" (DM-06 84/110)
RACE_MYSTERY_TOTEM		=0x2f	--Introduced by "Bliss Totem, Avatar of Luck" (DM-06 91/110)
RACE_SNOW_FAERIE		=0x30	--Introduced by "Charmilia, the Enticer" (DM-06 94/110)
RACE_VOLCANO_DRAGON		=0x31	--Introduced by "Magmadragon Jagalzor" (DM-08 4/55)
RACE_MECHA_DEL_SOL		=0x32	--Introduced by "Misha, Channeler of Suns" (DM-08 10/55)
RACE_ZOMBIE_DRAGON		=0x33	--Introduced by "Necrodragon Galbazeek" (DM-08 32/55)
RACE_EARTH_DRAGON		=0x34	--Introduced by "Terradragon Gamiratar" (DM-08 54/55)
RACE_SOLTROOPER			=0x35	--Introduced by "Bulgluf, the Spydroid" (DM-10 12/110)
RACE_CYBER_MOON			=0x36	--Introduced by "Ardent Lunatron" (DM-10 29/110)
RACE_MERFOLK			=0x37	--Introduced by "Mystic Magician" (DM-10 36/110)
RACE_PANDORAS_BOX		=0x38	--Introduced by "Benzo, the Hidden Fury" (DM-10 45/110)
RACE_MELT_WARRIOR		=0x39	--Introduced by "Burnwisp Lizard" (DM-10 64/110)
RACE_WILD_VEGGIES		=0x3a	--Introduced by "Hustle Berry" (DM-10 84/110)
RACE_SPIRIT_QUARTZ		=0x3b	--Introduced by "Deklowaz, the Terminator" (DM-10 S10/S10)
RACE_PHOENIX			=0x3c	--Introduced by "Soul Phoenix, Avatar of Unity" (DM-12 5/55)
RACE_STARNOID			=0x3d	--Introduced by "Wise Starnoid, Avatar of Hope" (DM-12 S2/S5)
RACE_NAGA				=0x3e	--Introduced by "Cruel Naga, Avatar of Fate" (DM-12 S3/S5)
RACE_PEGASUS			=0x3f	--Introduced by "Aura Pegasus, Avatar of Life" (DM-12 S5/S5)
RACE_COSMO_WALKER		=0x40	--Introduced by "Cabalt, the Patroller" (DM-14 13/110)
RACE_BIG_MUSCLE			=0x41	--Introduced by "Dynamite Peak" (DM-14 31/110)
RACE_WONDER_TRICK		=0x42	--Introduced by "Innocent, the Invoked" (DM-14 37/110)
RACE_SPLASH_QUEEN		=0x43	--Introduced by "Rosa Rossa" (DM-14 81/110)
RACE_GARGOYLE			=0x44	--Introduced by "Telescope Horn" (DM-14 88/110)
RACE_FEATHERNOID		=0x45	--Introduced by "Pyuzero, Prince of the South Wind" (DM-14 99/110)
RACE_ARC_SERAPHIM		=0x46	--Introduced by "Arac Kai Bades, Spirit Knight" (DM-19 2/110)
RACE_GRAND_DEVIL		=0x47	--Introduced by "Fuuma Soul Avals" (DM-19 5/110)
RACE_TYRANNO_DRAKE		=0x48	--Introduced by "Ribengios Dragoon" (DM-19 6/110)
RACE_DREAMMATE			=0x49	--Introduced by "Red Jackal, Raider of the North Sea" (DM-19 8/110)
RACE_GREAT_MECHA_KING	=0x4a	--Introduced by "Steel-Armor Benkeroth" (DM-19 12/110)
RACE_DYNAMO				=0x4b	--Introduced by "Steel-Armor Benkeroth" (DM-19 12/110)
RACE_DEEP_MARINE		=0x4c	--Introduced by "Snipe Alpheras" (DM-19 57/110)
RACE_BRAVE_SPIRIT		=0x4d	--Introduced by "Sag Panel of Eradication" (DM-19 91/110)
RACE_VEHICLE_BEE		=0x4e	--Introduced by "General Kuwagatan" (DM-19 S9/S10)
RACE_MACHINE_HERO		=0x4f	--Introduced by "Captain Gyro" (DM-20 22/55)
RACE_SAINT_HEAD			=0x50	--Introduced by "Manitus, Protection Spirit" (DM-20 53/55)
RACE_APOLLONIA_DRAGON	=0x51	--Introduced by "Spell Del Fin, Light Divine Dragon" (DM-22 1/55)
RACE_POSEIDIA_DRAGON	=0x52	--Introduced by "Spell Great Blue, Blue Divine Dragon" (DM-22 2/55)
RACE_GOD				=0x53	--Introduced by "God Apollonia Pegasus" (DM-24 1/110)
RACE_LOST_CRUSADER		=0x54	--Introduced by "Glen Bramsley, Red Destroyer of Gaia" (DM-24 9/110)
RACE_WORLD_BIRD			=0x55	--Introduced by "Miracle Rumba" (DM-27 S4/S5)
RACE_WORLD_DRAGON		=0x56	--Introduced by "Perfect Earth, Planetary Dragon" (DM-27 S5/S5)
RACE_BLUE_MONSTER		=0x57	--Introduced by "Deepsea Searcher" (DM-28 3/55)
RACE_KNIGHT				=0x58	--Introduced by "King Maximillian, the Ice Fang" (DM-28 4/55)
RACE_FLAME_MONSTER		=0x59	--Introduced by "Max, Crimson Blade Lord" (DM-28 7/110)
RACE_SAMURAI			=0x5a	--Introduced by "Dragon Gear - Musha Legend" (DM-28 8/110)
RACE_SHINE_MONSTER		=0x5b	--Introduced by "Pure Unicorn" (DM-28 12/110)
RACE_DARK_MONSTER		=0x5c	--Introduced by "Darkness Limit" (DM-28 25/110)
RACE_EMERALD_MONSTER	=0x5d	--Introduced by "Paol Nature" (DM-28 37/110)
RACE_SHINOBI			=0x5e	--Introduced by "Orochi of the Hidden Blade" (DM-29 2/55)
RACE_ORIGIN				=0x5f	--Introduced by "Amaterasu, Founder of the Blue Wolves" (DM-31 10/55)
RACE_LUNATIC_EMPEROR	=0x60	--Introduced by "Spiral Moon, the Enlightened" (DM-32 47/110)
RACE_GAIA_COMMAND		=0x61	--Introduced by "Auravine, Earth's Grasp" (DM-32 S10/S10)
RACE_CREATOR			=0x62	--Introduced by "Saga, the Almighty Creator" (DMC-57 6/39)
RACE_LUNAS_SUN_GEYSER	=0x63	--Introduced by "Galaxy Operation Theta, the Super Enlightened" (DM-35 2/55)
RACE_FLAME_COMMAND		=0x64	--Introduced by "Tornado Shiva Double Cross, Blastdragon" (DM-36 8/110)
RACE_SOUL_COMMAND		=0x65	--Introduced by "Final Doppel" (DM-39 5/55)
RACE_ALIEN				=0x66	--Introduced by "V-Y, the Patroller" (DM-39 6/55)
RACE_WORLD_COMMAND		=0x67	--Introduced by "Diabolos Zeta, Temporal Ruler" (DM-39 S5a/S5)
RACE_RED_COMMAND_DRAGON	=0x68	--Introduced by "Raging Dragon Lord" (DMX-01 9/40)
RACE_HUNTER				=0x69	--Introduced by "Raging Dragon Lord" (DMX-01 9/40)
RACE_RAINBOW_COMMAND_DRAGON	=0x6a	--Introduced by "Dead Sea Dragon" (DMX-01 15/40)
RACE_EGG					=0x6b	--Introduced by "Dragon Flare Egg" (DMR-01 32/110)
RACE_DEVIL_COMMAND_DRAGON	=0x6c	--Introduced by "Gallows Devil Dragon, Dead Sea Dragon" (DMR-01 53b/110+59b/110)
RACE_KING_COMMAND_DRAGON	=0x6d	--Introduced by "Gaial King Dragon, Raging Dragon Lord" (DMR-01 60b/110+62b/110)
RACE_BLUE_COMMAND_DRAGON	=0x6e	--Introduced by "Insight Indigo Kaiser" (DMR-02 1/54)
RACE_BLACK_COMMAND_DRAGON	=0x6f	--Introduced by "THE FINAL Kaiser" (DMX-04 1/16)
RACE_SHINING_COMMAND_DRAGON	=0x70	--Introduced by "Crazy Carnival! Saint Chan-Merrie" (DMX-04 4b/16)
RACE_WHITE_COMMAND_DRAGON	=0x71	--Introduced by "White TENMTH Kaiser" (DMX-05 1a/16)
RACE_UNKNOWN				=0x72	--Introduced by "Codename Sorge" (DMR-03 S5/S5)
RACE_SUMO_WRESTLER_COMMAND	=0x73	--Introduced by "Nibai Nibai, Mysterious Fire Yokozuna" (DMX-06 2/21)
RACE_HERO					=0x74	--Introduced by "Yuu, Passionate Duel Hero" (DMX-06 21/21)
RACE_BEAST_COMMAND			=0x75	--Introduced by "Jin, the Ogre Blade ~Crimson Rage~" (DMX-06 V1a/V1)
RACE_GAO_MONSTER			=0x76	--Introduced by "Deis Orthrus, Brave Beast King" (DMR-04 15/55)
RACE_CURRY_BREAD			=0x77	--Introduced by "Katta Kirifuda, Curry Bread Boy" (P23/Y11)
RACE_UNNOISE				=0x78	--Introduced by "Kachamashigu, Spirit of Rays" (DMD-06 2/14)
RACE_ZENITH					=0x79	--Introduced by "Lionel, Zenith of "Ore"" (DMR-05 V1/V3)
RACE_IDOL					=0x7a	--Introduced by "Idolmaster Leo" (P58/Y11)
RACE_PIANIST				=0x7b	--Introduced by "VAN Beat, Battlefield Pianist" (P67/Y11)
RACE_GREEN_COMMAND_DRAGON	=0x7c	--Introduced by "Danchino Kaiser, Mother Green Oni Dragon" (DMD-07 5/24)
RACE_TRISTONE				=0x7d	--Introduced by "Niyare" (DMR-07 33/55)
RACE_SPECIAL_CLIMAX			=0x7e	--Introduced by "Great Waste" (DMX-12 b21/???)
RACE_ORACLE					=0x7f	--Introduced by "Saicho, Satori's Oracle" (DMX-13 12/36)
RACE_OUTRAGE				=0x80	--Introduced by "Smith, Breaking Right" (DMX-13 26/36)
RACE_CHILDREN				=0x81	--Introduced by "Violent Children" (DMR-08S 4/7)
RACE_ORACLION				=0x82	--Introduced by "Alternative, Sacred Cavalry" (DMD-10 1/14)
RACE_OUTRAGE_MAX			=0x83	--Introduced by "Ragnarok, the Clock" (P18/Y12)
RACE_GOD_NOVA				=0x84	--Introduced by "Daft Punk, Lord of Demons Right God" (DMR-09 1/110)
RACE_MAGICAL_MONSTER		=0x85	--Introduced by "Karre Ganejar, Metal Lamp Djinn" (P65/Y11)
RACE_GOD_NOVA_OMG			=0x86	--Introduced by "Electraglide, Fallen Left God" (DMR-11 3/55)
RACE_HUMAN_BAKU				=0x87	--Introduced by "Glenmalt, Explosive Swordsman" (DMR-12 14/55)
RACE_JUSTICE_WING			=0x88	--Introduced by "Kigunashion, Pure White Wings" (DMR-12 21/55)
RACE_LIQUID_PEOPLE_SEN		=0x89	--Introduced by "Bat Mask, Aqua Warrior" (DMR-12 39/55)
RACE_OUTRAGE_OMG			=0x8a	--Introduced by "Katsumugen, Climax" (DMR-12 V2/V2)
RACE_CRYSTAL_COMMAND_DRAGON	=0x8b	--Introduced by "iQ Cloypaedia, Dragment Symbol" (DMD-17 1/14)
RACE_JURASSIC_COMMAND_DRAGON=0x8c	--Introduced by "Triprex, Growth King" (DMX-16 36/84)
RACE_GAIAL_COMMAND_DRAGON	=0x8d	--Introduced by "Gaigensui, Striking Hero" (DMR-13 7/110)
RACE_DRAGUNER				=0x8e	--Introduced by "Everrose, Dragon Edge" (DMR-13 13/110)
RACE_FUNKY_KNIGHTMARE		=0x8f	--Introduced by "Uroborof, Dragon Edge" (DMR-13 25/110)
RACE_BEAST_FOLK_GO			=0x90	--Introduced by "Sasoris, Dragon Edge" (DMR-13 36/110)
RACE_DARK_KNIGHTMARE		=0x91	--Introduced by "Vicious Deslar, Dream Knight" (DMR-16極 2/54)
RACE_MEGA_COMMAND_DRAGON	=0x92	--Introduced by "Gou Break Dragon" (DMR-16極 3/54)
RACE_SNOW_FAERIE_KAZE		=0x93	--Introduced by "Bell the Elemental" (DMR-16極 16/54)
RACE_CYBER_VIRUS_KAI		=0x94	--Introduced by "Octopuscal, Great Captain" (DMR-16極 21/54)
RACE_FIRE_BIRD_EN			=0x95	--Introduced by "Jet Polka" (DMR-16極 29/54)
RACE_JUSTICE_ORB			=0x96	--Introduced by "Ribulibarrier, Holy Ball" (DMR-16真 5/54)
RACE_INVADER				=0x97	--Introduced by "Bhuddi, Three Kingdoms" (DMR-17 1/94)
RACE_REVOLUTIONARY			=0x98	--Introduced by "Cylinder, Revolution Dragon Formula" (DMR-17 3/94)
RACE_MAGIC_COMMAND			=0x99	--Introduced by "Pocard, Eureka" (DMR-17 4/94)
RACE_GUERRILLA_COMMAND		=0x9a	--Introduced by "Runbomber, Beast Army" (DMR-17 26/94)
RACE_SONIC_COMMAND			=0x9b	--Introduced by "Burunburu, Invader" (DMR-17 48/94)
RACE_QQQ					=0x9c	--Introduced by "Unidentified" (DMR-18 S3/S9)
RACE_S_RANK_INVADER			=0x9d	--Introduced by "Dead Dollar, S-Rank Zombie" (DMR-19 17/87)
RACE_INITIALS				=0x9e	--Introduced by "Trooper, Forbidden U" (DMR-19 43/87)
RACE_WORLD_IDOL				=0x9f	--Introduced by "Ultimate Man" (DMX-22 115/???)
RACE_2016_CALENDAR			=0xa0	--Introduced by "January" (DMX-22 b1/???)
RACE_OUTRAGE_NYANKO			=0xa1	--Introduced by "Nyannyan, Nyanko Rage" (DMX-22 b22/???)
RACE_NARRATOR				=0xa2	--Introduced by "Narrataro, Explosive Passion" (DMX-22 b33/???)
RACE_METAL_COMMAND_DRAGON	=0xa3	--Introduced by "Kushala Daora, Steel Dragon" (DMX-22 b109/???)
RACE_OUTRAGE_WANKO			=0xa4	--Introduced by "Wanwanwan, Wankorage" (DMX-22 b110/???)
RACE_ELDER_DRAGON			=0xa5	--Introduced by "Nicol Bolas" (DMX-22 b128/???)
RACE_PLANESWALKER			=0xa6	--Introduced by "Nicol Bolas" (DMX-22 b128/???)
RACE_SPECIAL_THANKS			=0xa7	--Introduced by "Great Thanks" (DMX-22 b160/???)
RACE_HUMAN_JYA				=0xa8	--Introduced by "Seriously Invincible Grandpa" (P56/Y14)
RACE_THE_ANSWER				=0xa9	--Introduced by "Duerou, Weapon of Dreams" (DMR-20 29/70)
RACE_TEAM_HAMUKATSU			=0xaa	--Introduced by "Briking, Deluxe" (DMD-29 1/13)
RACE_TEAM_DOREMI			=0xab	--Introduced by "Belufare, Great Cathedral" (DMD-30 1/13)
RACE_ANGEL_DRAGON			=0xac	--Introduced by "Kernel, Blue Stagnation Dragon Elemental" (DMD-30 3/13)
RACE_MASTER_INITIALS		=0xad	--Introduced by "Forbidden Voltron, D2-V" (DMD-31 1/12)
RACE_JURASSIC_DRAGON		=0xae	--Introduced by "Amurex, Rainbowkind" (DMR-21 8/94)
RACE_TEAM_DAMAMA			=0xaf	--Introduced by "Wekapipo, Tatu" (DMR-21 22/94)
RACE_TEAM_TECH				=0xb0	--Introduced by "Jiin, "Question 3"" (DMR-21 24/94)
RACE_CRYSTAL_DRAGON			=0xb1	--Introduced by "Noron, "Question 2"" (DMR-21 52/94)
RACE_DEMON_DRAGON			=0xb2	--Introduced by "Tamagineil, Second Seed" (DMR-21 54/94)
RACE_TEAM_ACME				=0xb3	--Introduced by "Tamagineil, Second Seed" (DMR-21 54/94)
RACE_MEGA_DRAGON			=0xb4	--Introduced by "Katsuemon, Blade 3" (DMR-21 56/94)
RACE_MILKBOY				=0xb5	--Introduced by "BoleBole, Bei B" (DMR-22 38/74)
RACE_INVADER_ZERO			=0xb6	--Introduced by "The ZERO, Black Speed" (DMR-22 54/74)
RACE_MASTER_REVOLUTIONARY	=0xb7	--Introduced by "Wachagona, Muen Zangu" (DMR-22 S5/S9)
RACE_FORBIDDEN_SONIC_COMMAND=0xb8	--Introduced by "Dokindam Black" (DMD-35 2/12)
RACE_INITIALS_X				=0xb9	--Introduced by "Dorhakaba, Final Forbidden Delta" (DMR-23 43/74)
RACE_METALLICA				=0xba	--Introduced by "Phantasm, Moon's Radiance" (DMR-23 S1/S9)
RACE_JOKERS					=0xbb	--Introduced by "Dotsuking, Three Crown King" (DMRP-01 1/93)
RACE_MUTOPIA				=0xbc	--Introduced by "Octoba, Sublime Knowledge" (DMRP-01 4/93)
RACE_SPECIALS				=0xbd	--Introduced by "Hoseters 5" (DMRP-01 5/93)
RACE_MAFI_GANG				=0xbe	--Introduced by "Stomak, Electric Killer" (DMRP-01 6/93)
RACE_BEAT_JOCKEY			=0xbf	--Introduced by "Block King" (DMRP-01 8/93)
RACE_GRANSECT				=0xc0	--Introduced by "Shizenseijin" (DMRP-01 10/93)
RACE_DRAGON_GUILD			=0xc1	--Introduced by "Borsche, Dragon Car" (DMRP-01 47/93)
RACE_JUDGMENT_EMBLEM		=0xc2	--Introduced by "One Eye's Judgment" (DMBD-04 8/15)
RACE_SABAKIST				=0xc3	--Introduced by "Tsudoino Sabato" (DMRP-04裁 12/93)
RACE_MASTER_DG				=0xc4	--Introduced by "Savaak DG" (DMRP-04裁 M1/M1)
RACE_MASTER_DRAGON			=0xc5	--Introduced by "Savark ~Judgment for Justice~" (P84/Y16)
RACE_MAGIC_TOOL				=0xc6	--Introduced by "Vogaiga, Darma" (DMRP-04魔 5/61)
RACE_MASTER_DOLSZAK			=0xc7	--Introduced by "De Szark" (DMRP-04魔 MD1/MD1)
RACE_DOLSZAK				=0xc8	--Introduced by "De Rupansa" (DMSD-06 1/15)
RACE_JUDGMENT_EMBLEM_Z		=0xc9	--Introduced by "Kokuchono Seisai Zett" (DMSD-07 5/13)
RACE_SPRIGGAN				=0xca	--Introduced by "Messer Schmitt" (DMEX-03 G1/G3)
RACE_GRANSECT_HAZARD		=0xcb	--Introduced by "Baraghiara, Violent Heaven" (DMBD-08 a-1/13)
RACE_WONDERFORCE			=0xcc	--Introduced by "Haileader, Play Music" (DMRP-09 1/102)
RACE_TRICKS					=0xcd	--Introduced by "Ganime De, Kyokugenchi" (DMRP-09 4/102)
RACE_DELETRON				=0xce	--Introduced by "Ganime De, Kyokugenchi" (DMRP-09 4/102)
RACE_TRINITY_COMMAND		=0xcf	--Introduced by "Dead Damned, Triple S-Rank Disaster" (DMBD-10 2/18)
RACE_FLAME_BEAST			=0xd0	--Introduced by "Balrogleno" (DMRP-11 93/102)
RACE_DRAGON_CODE			=0xd1	--Introduced by "Code:Heaven" (DMRP-11 M2/M3)
RACE_DRAGONS_ZERO			=0xd2	--Introduced by "Zero" (DMRP-11 超㊙1/超㊙1)
RACE_ZEROLIST				=0xd3	--Introduced by "Astel, Zero Star" (DMRP-12 48/104)
RACE_MONSTER				=0xd4	--Introduced by "Beholder, Orderly General" (DMEX-08 17/???)
RACE_NEET					=0xd5	--Introduced by "Choromatsu, Nature's Third Son" (DMEX-08 47/???, 48/???)
RACE_GANG					=0xd6	--Introduced by "Coco Yuyu Doxon, Dogenzaka Mongoose" (DMEX-08 52a/???, 52b/???)
RACE_ELDRAZI				=0xd7	--Introduced by "Emrakul, the Aeons Torn" (DMEX-08 91/???)
RACE_GOBLIN					=0xd8	--Introduced by "Mons's Goblin Raiders" (DMEX-08 199/???)
RACE_MILKGIRL				=0xd9	--Introduced by "Akalin Hyolin, Bei B" (DMEX-08 207/???)
RACE_RAINBOW_DRAGON			=0xda	--Introduced by "Ryujinmaru" (DMEX-08 304b/???)
RACE_HOLY_DRAGON			=0x7ff	--Introduced by "Altimeth, Holy Divine Dragon" (Game Original)
--Race Category (0x800-0x9ff)
RACECAT_DRAGON				=0x800	--Supported by "Kachua, Keeper of the Icegate" (DM-08 5/55)
RACECAT_COMMAND				=0x801	--(TBA)
RACECAT_CYBER				=0x802	--(TBA)
RACECAT_KNIGHTMARE			=0x803	--(TBA)
--Name Category (0xa00-0xfff)
NAMECAT_SWORD_FLASH			=0xa00	--Supported by "Balrun Shizou" (DM-30 16/55)
NAMECAT_SWORD_FLASH_DRAGON	=0x1a00	--Supported by "Borkov Shion" (DM-35 31/55)
NAMECAT_B_SWORD_FLASH_DRAGON=0x3a00	--Supported by "Bullet "Shirou" Barrett" (DM-29 16/55)
NAMECAT_KEN					=0xa01	--(reserved)
NAMECAT_KEN_CRIMSON_LORD	=0x3a01	--Supported by "Wan Ken, Crimson Lord ~Moonlight Howl~" (DM-32 60/110)
NAMECAT_KEN_GOU_CRIMSON_LORD=0x5a01	--Supported by "Wan Ken, Crimson Lord ~Moonlight Howl~" (DM-32 60/110)
NAMECAT_WAN_KEN_CRIMSON_LORD=0x6a01	--Supported by "Ken, Crimson Lord ~Journey's Beginning~" (DM-32 101/110)
NAMECAT_LORD_GOU_KEN		=0xaa01	--Supported by "Ken Gou, Crimson Lord ~The Sundering~" (DM-33 16/55)
NAMECAT_KEN_GEKI			=0xca01	--Supported by "Lord Gou Ken ~Symphony of Swords~" (DM-34 15/55)
NAMECAT_LUPIA				=0xa02	--Supported by "Bolshack NEX" (DM-32 S8/S10)
NAMECAT_WHITE_KNIGHT		=0xa03	--Supported by "Astinos, White Knight Spirit" (DM-33 36/55)
NAMECAT_NEX					=0xa04	--Supported by "Cutie Lupia" (DM-34 41/55)
NAMECAT_AKU_AND_ZEN			=0xa05	--Supported by "Saga, God of Destruction" (DM-34+1S 3S/3S)
NAMECAT_ROMANOV				=0xa06	--Supported by "Dark Division, Demonic Eye Beast" (DMC-58 5/16)
NAMECAT_SPARK				=0xa07	--Supported by "Sun's Creed, Spirit of Revelation" (DM-36 2/110)
NAMECAT_HOLY_SPARK			=0x1a07	--Supported by "Alca Kid, Holy Elemental" (DMX-21 33/70)
NAMECAT_HYPERSPATIAL		=0xa08	--Supported by "Flame Shiva Double Cross, Blastdragon" (DM-36 60/110)
NAMECAT_DOUBLE_CROSS		=0xa09	--Supported by "Chai Aini" (DM-36 97/110)
NAMECAT_GENJI_DOUBLE_CROSS	=0x1a09	--Supported by "Reppi SP Aini" (DM-39 30/55)
NAMECAT_EMPEROR_OF_THE_GODS	=0xa0a	--Supported by "Suva, Temporal Menace" (DMC-63 1a/19)
NAMECAT_ZETA				=0xa0b	--Supported by "Darkness Dober" (DM-37 45/55)
NAMECAT_AWAKENED			=0xa0c	--Supported by "Words from Beyond" (DM-39 10/55)
NAMECAT_FIVE_STAR			=0xa0d	--Supported by "Tulk SP" (DM-39 21/55)
NAMECAT_REAPER				=0xa0e	--Supported by "Belbel, Reaper Doll" (DM-39 28/55)
NAMECAT_AINI				=0xa0f	--Supported by "GENJI Blaster" (DM-39 32/55)
NAMECAT_G_HOGAN				=0xa10	--Supported by "Ribbity SP" (DM-39 40/55)
NAMECAT_GANVEET				=0xa11	--Supported by "Dark Strike SP" (DM-39 45/55)
NAMECAT_KANKURO				=0xa12	--Supported by "Princess Cub SP" (DM-39 53/55)
NAMECAT_BOLSHACK			=0xa13	--Supported by "Gaial Bolshack, Raging Dragon" (P21/Y10)
NAMECAT_VICTORY				=0xa14	--Supported by "Kaiser Flame, Secret Flame Dragon" (DMR-06 30/55)
NAMECAT_HEAVENS				=0xa15	--Supported by "Kibbate Cat, Heaven's Gate Elemental" (DMX-11 38/84)
NAMECAT_PARLOCK				=0xa16	--Supported by "Parlock, Sacred Prayer" (DMX-15 1/30)
NAMECAT_PRIN				=0xa17	--Supported by "Kaiser Prince, Flame Dragon Prince" (DMR-11 5/55) ("Prince", "Princess" and "Springs")
NAMECAT_SHEN				=0xa18	--Supported by "Lance of Tonginus" (DMR-11 7/55)
NAMECAT_TESTA_ROSSA			=0xa19	--Supported by "Testa Rossa, Last Burning" (DMR-11 S5/S5)
NAMECAT_RYUSEI				=0xa1a	--Supported by "Ryusei, the End of Conclusion" (DMR-12 S5/S5)
NAMECAT_GAIAL				=0xa1b	--Supported by "Gaial, Leader Dragon Sword" (DMD-18 2a/20)
NAMECAT_PARAS				=0xa1c	--Supported by "Parasrex, Chain Parasitic Eye" (DMR-15 18/55)
NAMECAT_GUERRILLA_DIVISION	=0xa1d	--Supported by "Tsurato Usutora, Leader of Division" (DMR-16極 19/54)
NAMECAT_BOLMETEUS			=0xa1e	--Supported by "Bolmeteus White Flare" (DMD-24 11/37)
NAMECAT_BOLMETEUS_MUSHA_DRAGON	=0x1a1e	--Supported by "Bolshack Yamato Dragon" (DM-26 S2/S5)
NAMECAT_BOLMETEUS_STEEL_DRAGON	=0x2a1e	--Supported by "Legend of Hope and Victory" (DMD-24 13/37)
NAMECAT_MUSHA					=0xa1f	--Supported by "Dragon Gear - Sengoku Topper Armor" (DMX-21 13/70)
NAMECAT_YAMATO					=0xa20	--Supported by "Dragon Gear - Sengoku Topper Armor" (DMX-21 13/70)
NAMECAT_LORD_OF_SPIRITS			=0xa21	--Supported by "Alca Kid, Holy Elemental" (DMX-21 33/70)
NAMECAT_BALLOM					=0xa22	--Supported by "Barlowe, Devil Priest" (DMX-21 40/70)
NAMECAT_BOLBERG					=0xa23	--Supported by "Great Earth" (DMX-21 46/70)
NAMECAT_DOKINDAM				=0xa24	--Supported by "Marmo, Forbidden C" (DMR-19 74/87)
NAMECAT_FORBIDDEN				=0xa25	--Supported by "FORBIDDEN STAR ~World's Last Day~" (DMR-23 FFL1a/FFL5)
NAMECAT_DG						=0xa26	--Supported by "DG ~Time of Judgment~" (P54/Y16)
NAMECAT_STORED_MAGIC			=0xa27	--Supported by "Pernore, Stored Magic" (DMRP-04裁 37/93)
NAMECAT_MEN						=0xa28	--Supported by "Charmeijin, Hundred Delivery" (DMRP-05 1/93)
NAMECAT_BRAIN					=0xa29	--Supported by "Neonkus, Palace Missionary" (DMRP-06 3/93)
NAMECAT_HAND					=0xa2a	--Supported by "Mad Demon Excellency" (DMRP-06 6/93)
NAMECAT_SCRAPPER				=0xa2b	--Supported by "Magmajigoku, Dragon Armored Car" (DMRP-06 7/93)
NAMECAT_TRAP					=0xa2c	--Supported by "Na Turalgo Danger" (DMRP-06 S9/S10)
--Reason
--The reason for sending a card to another location
REASON_DESTROY		=0x1		--Destroyed
REASON_RELEASE		=0x2		--(unused)
REASON_TEMPORARY	=0x4		--Temporarily moved
REASON_MATERIAL		=0x8		--(unused)
REASON_SUMMON		=0x10		--(unused)
REASON_BATTLE		=0x20		--Battle destroyed
REASON_EFFECT		=0x40		--Effect
REASON_COST			=0x80		--Cost
REASON_ADJUST		=0x100		--(unused)
REASON_LOST_TARGET	=0x200		--(unused)
REASON_RULE			=0x400		--Rule
REASON_SPSUMMON		=0x800		--(unused)
REASON_DISSUMMON	=0x1000		--(unused)
REASON_FLIP			=0x2000		--(unused)
REASON_DISCARD		=0x4000		--Discarded
REASON_RDAMAGE		=0x8000		--(unused)
REASON_RRECOVER		=0x10000	--(unused)
REASON_RETURN		=0x20000	--(unused)
REASON_FUSION		=0x40000	--(unused)
REASON_SYNCHRO		=0x80000	--(unused)
REASON_RITUAL		=0x100000	--(unused)
REASON_XYZ			=0x200000	--(unused)
REASON_REPLACE		=0x1000000	--Substituted
REASON_DRAW			=0x2000000	--(unused)
REASON_REDIRECT		=0x4000000	--(unused)
REASON_REVEAL		=0x8000000	--(unused)
REASON_LINK			=0x10000000	--(unused)
REASON_BREAK		=0x20000000	--Shield broken
--Location Reason
LOCATION_REASON_TOFIELD		=0x1	--(unused)
LOCATION_REASON_CONTROL		=0x2	--(unused)
LOCATION_REASON_COUNT		=0x4	--(unused, only available in YGOPro Percy)
--Win Reason
WIN_REASON_DECKOUT		=0x2	--Ran out of cards in the deck
WIN_REASON_INVALID		=0x10	--Invalid deck
WIN_REASON_BOMBAZAR		=0x11	--Bombazar, Dragon of Destiny
--Summon Type
SUMMON_TYPE_NORMAL		=0x10000000	--(unused)
SUMMON_TYPE_ADVANCE		=0x11000000	--(unused)
SUMMON_TYPE_DUAL		=0x12000000	--(unused)
SUMMON_TYPE_FLIP		=0x20000000	--(unused)
SUMMON_TYPE_SPECIAL		=0x40000000	--(unused)
SUMMON_TYPE_FUSION		=0x43000000	--(unused)
SUMMON_TYPE_RITUAL		=0x45000000	--(unused)
SUMMON_TYPE_SYNCHRO		=0x46000000	--(unused)
SUMMON_TYPE_NONEVOLVE	=0x49000000	--Summon by paying mana
SUMMON_TYPE_EVOLVE		=0x49000100	--Evolve
SUMMON_TYPE_PENDULUM	=0x4a000000	--(unused)
SUMMON_TYPE_LINK		=0x4c000000	--(unused)
--Summon Value
SUMMON_VALUE_SELF					=0x1	--(unused)
SUMMON_VALUE_DARK_FUSION			=0x10	--(unused)
SUMMON_VALUE_BLACK_GARDEN			=0x11	--(unused)
SUMMON_VALUE_SYNCHRO_MATERIAL		=0x12	--(unused)
SUMMON_VALUE_DARK_SANCTUARY			=0x13	--(unused)
SUMMON_VALUE_MILLENNIUM_REVELATION	=0x14	--(unused)
SUMMON_VALUE_LV						=0x1000	--(unused)
SUMMON_VALUE_GLADIATOR				=0x2000	--(unused)
SUMMON_VALUE_EVOLTILE				=0x4000	--(unused)
--Card Status
STATUS_DISABLED				=0x0001		--(unused)
STATUS_TO_ENABLE			=0x0002		--(unused)
STATUS_TO_DISABLE			=0x0004		--(unused)
STATUS_PROC_COMPLETE		=0x0008		--(unused)
STATUS_SET_TURN				=0x0010		--(unused)
STATUS_NO_LEVEL				=0x0020		--(unused)
STATUS_BATTLE_RESULT		=0x0040		--(unused)
STATUS_SPSUMMON_STEP		=0x0080		--(unused)
STATUS_FORM_CHANGED			=0x0100		--(unused)
STATUS_SUMMONING			=0x0200		--(unused)
STATUS_EFFECT_ENABLED		=0x0400		--(unused)
STATUS_SUMMON_TURN			=0x0800		--(unused)
STATUS_DESTROY_CONFIRMED	=0x1000		--Confirmed to be destroyed
STATUS_LEAVE_CONFIRMED		=0x2000		--(unused)
STATUS_BATTLE_DESTROYED		=0x4000		--Lost a battle
STATUS_COPYING_EFFECT		=0x8000		--Copying another card's effect
STATUS_CHAINING				=0x10000	--(unused)
STATUS_SUMMON_DISABLED		=0x20000	--(unused)
STATUS_ACTIVATE_DISABLED	=0x40000	--(unused)
STATUS_EFFECT_REPLACED		=0x80000	--(unused)
STATUS_FUTURE_FUSION		=0x100000	--(unused)
STATUS_ATTACK_CANCELED		=0x200000	--Attacking card's attack is negated
STATUS_INITIALIZING			=0x400000	--(unused)
STATUS_ACTIVATED			=0x800000	--(unused, only available in YGOPro Percy)
STATUS_JUST_POS				=0x1000000	--(unused)
STATUS_CONTINUOUS_POS		=0x2000000	--(unused)
STATUS_FORBIDDEN			=0x4000000	--(unused)
STATUS_ACT_FROM_HAND		=0x8000000	--(unused)
STATUS_OPPO_BATTLE			=0x10000000	--Battled against opponent's card
STATUS_FLIP_SUMMON_TURN		=0x20000000	--(unused)
STATUS_TO_BZONE_TURN		=0x40000000	--Put into the battle zone this turn
--Assume
ASSUME_CODE			=1	--(unused)
ASSUME_TYPE			=2	--(unused)
ASSUME_LEVEL		=3	--(unused)
ASSUME_RANK			=4	--(unused)
ASSUME_ATTRIBUTE	=5	--(unused)
ASSUME_RACE			=6	--(unused)
ASSUME_ATTACK		=7	--(unused)
ASSUME_DEFENSE		=8	--(unused)
ASSUME_LINK			=9	--(unused, only available in YGOPro Percy)
ASSUME_LINKMARKER	=10	--(unused, only available in YGOPro Percy)
--Link Marker
LINK_MARKER_BOTTOM_LEFT		=0x001	--(unused)
LINK_MARKER_BOTTOM			=0x002	--(unused)
LINK_MARKER_BOTTOM_RIGHT	=0x004	--(unused)
LINK_MARKER_LEFT			=0x008	--(unused)
LINK_MARKER_RIGHT			=0x020	--(unused)
LINK_MARKER_TOP_LEFT		=0x040	--(unused)
LINK_MARKER_TOP				=0x080	--(unused)
LINK_MARKER_TOP_RIGHT		=0x100	--(unused)
--Counter
COUNTER_WITHOUT_PERMIT		=0x1000	--(unused)
COUNTER_NEED_ENABLE			=0x2000	--(unused)
--Phase
PHASE_DRAW			=0x01	--Draw Phase
PHASE_STANDBY		=0x02	--Standby Phase
PHASE_MAIN1			=0x04	--Main Phase 1
PHASE_BATTLE_START	=0x08	--Start Step
PHASE_BATTLE_STEP	=0x10	--Battle Step
PHASE_DAMAGE		=0x20	--Damage Step
PHASE_DAMAGE_CAL	=0x40	--Damage calculation
PHASE_BATTLE		=0x80	--End Step
PHASE_MAIN2			=0x100	--Main Phase 2
PHASE_END			=0x200	--End Phase
--Player
PLAYER_ONE			=0		--Player who goes first
PLAYER_TWO			=1		--Player who goes second
PLAYER_NONE			=2		--No players
PLAYER_ALL			=3		--All players
PLAYER_OWNER		=nil	--player=PLAYER_OWNER in Duel.Sendto..(targets, player, reason)
PLAYER_SELF			=0		--player=PLAYER_SELF in Effect.SetCondition(Auxiliary.Function(player)), etc.
PLAYER_OPPO			=1		--player=PLAYER_OPPO in Effect.SetCondition(Auxiliary.Function(player)), etc.
--Chain Information
CHAININFO_CHAIN_COUNT			=0x01	--(unused)
CHAININFO_TRIGGERING_EFFECT		=0x02	--(unused)
CHAININFO_TRIGGERING_PLAYER		=0x04	--(unused)
CHAININFO_TRIGGERING_CONTROLER	=0x08	--(unused)
CHAININFO_TRIGGERING_LOCATION	=0x10	--(unused)
CHAININFO_TRIGGERING_SEQUENCE	=0x20	--(unused)
CHAININFO_TARGET_CARDS			=0x40	--(unused)
CHAININFO_TARGET_PLAYER			=0x80	--(unused)
CHAININFO_TARGET_PARAM			=0x100	--(unused)
CHAININFO_DISABLE_REASON		=0x200	--(unused)
CHAININFO_DISABLE_PLAYER		=0x400	--(unused)
CHAININFO_CHAIN_ID				=0x800	--(unused)
CHAININFO_TYPE					=0x1000	--(unused)
CHAININFO_EXTTYPE				=0x2000	--(unused)
CHAININFO_TRIGGERING_POSITION	=0x4000	--(unused)
--The following is not available in YGOPro Percy
CHAININFO_TRIGGERING_CODE		=0x8000		--(unused)
CHAININFO_TRIGGERING_CODE2		=0x10000	--(unused)
CHAININFO_TRIGGERING_LEVEL		=0x40000	--(unused)
CHAININFO_TRIGGERING_RANK		=0x80000	--(unused)
CHAININFO_TRIGGERING_ATTRIBUTE	=0x100000	--(unused)
CHAININFO_TRIGGERING_RACE		=0x200000	--(unused)
CHAININFO_TRIGGERING_ATTACK		=0x400000	--(unused)
CHAININFO_TRIGGERING_DEFENSE	=0x800000	--(unused)
--Reset
RESET_SELF_TURN		=0x10000000			--Reset on own turn (combined with RESET_PHASE)
RESET_OPPO_TURN		=0x20000000			--Reset on opponent's turn (combined with RESET_PHASE)
RESET_PHASE			=0x40000000			--Reset in a specific phase (combined with PHASE constant)
RESET_CHAIN			=0x80000000			--Reset when a Chain resolves
RESET_EVENT			=0x1000				--Reset under a specified condition (combined with following events)
RESET_CARD			=0x2000				--(unused)
RESET_CODE			=0x4000				--(unused)
RESET_COPY			=0x8000				--Reset the copied effect
--The following is used in combination with RESET_EVENT in SetReset
RESET_DISABLE		=0x00010000			--Reset when effect is negated (only applicable to owner==effect handler)
RESET_TURN_SET		=0x00020000			--Reset when face-down on the field
RESET_TOMANA		=0x00040000			--(unused)
RESET_TOGRAVE		=0x00080000			--Reset when put into the graveyard
RESET_TEMP_REMOVE	=0x00100000			--(unused)
RESET_TOHAND		=0x00200000			--Reset when put into the hand
RESET_TODECK		=0x00400000			--(unused)
RESET_LEAVE			=0x00800000			--Reset when left the battle zone
RESET_TOFIELD		=0x01000000			--(unused)
RESET_CONTROL		=0x02000000			--(unused)
RESET_OVERLAY		=0x04000000			--(unused)
RESET_MSCHANGE		=0x08000000			--(unused)
--Reset combinations
RESETS_STANDARD		=0x1fe0000			--RESET_TURN_SET+RESET_TOMANA+RESET_TOGRAVE+RESET_TEMP_REMOVE+RESET_TOHAND+RESET_TODECK+RESET_LEAVE+RESET_TOFIELD
RESETS_REDIRECT		=0xc7e0000			--RESETS_STANDARD+RESET_OVERLAY+RESET_MSCHANGE-RESET_LEAVE-RESET_TOFIELD (EFFECT_LEAVE_FIELD_REDIRECT)
--Effect Type
--Classification of effects
EFFECT_TYPE_SINGLE			=0x0001		--Effect applied to only a single card on the field
EFFECT_TYPE_FIELD			=0x0002		--Effect applied to all cards/players in a location
EFFECT_TYPE_EQUIP			=0x0004		--(unused)
EFFECT_TYPE_ACTIONS			=0x0008		--(unused)
EFFECT_TYPE_ACTIVATE		=0x0010		--(unused)
EFFECT_TYPE_FLIP			=0x0020		--(unused)
EFFECT_TYPE_IGNITION		=0x0040		--Ignition Effect
EFFECT_TYPE_TRIGGER_O		=0x0080		--Optional Trigger Effect
EFFECT_TYPE_QUICK_O			=0x0100		--Optional Quick Effect
EFFECT_TYPE_TRIGGER_F		=0x0200		--Mandatory Trigger Effect
EFFECT_TYPE_QUICK_F			=0x0400		--Mandatory Quick Effect
EFFECT_TYPE_CONTINUOUS		=0x0800		--Continuous Effect, non-Chaining effect
EFFECT_TYPE_XMATERIAL		=0x1000		--(unused)
EFFECT_TYPE_GRANT			=0x2000		--Effect granted to another card
EFFECT_TYPE_TARGET			=0x4000		--(unused, not available in YGOPro Percy)
--Flag
--Characteristics of effects
EFFECT_FLAG_INITIAL				=0x0001		--(unused)
EFFECT_FLAG_FUNC_VALUE			=0x0002		--(unused)
EFFECT_FLAG_COUNT_LIMIT			=0x0004		--(unused)
EFFECT_FLAG_FIELD_ONLY			=0x0008		--(unused)
EFFECT_FLAG_CARD_TARGET			=0x0010		--Targets cards
EFFECT_FLAG_IGNORE_RANGE		=0x0020		--Affects cards in all locations
EFFECT_FLAG_ABSOLUTE_TARGET		=0x0040		--(unused)
EFFECT_FLAG_IGNORE_IMMUNE		=0x0080		--Ignores effect immunity
EFFECT_FLAG_SET_AVAILABLE		=0x0100		--Affects face-down cards on the field
EFFECT_FLAG_CANNOT_NEGATE		=0x0200		--(unused)
EFFECT_FLAG_CANNOT_DISABLE		=0x0400		--Cannot be negated
EFFECT_FLAG_PLAYER_TARGET		=0x0800		--Targets players
EFFECT_FLAG_BOTH_SIDE			=0x1000		--(unused)
EFFECT_FLAG_COPY_INHERIT		=0x2000		--(unused)
EFFECT_FLAG_DAMAGE_STEP			=0x4000		--Can be activated during the Damage Step (not required for EFFECT_TYPE_SINGLE)
EFFECT_FLAG_DAMAGE_CAL			=0x8000		--Can be activated during damage calculation (not required for EFFECT_TYPE_SINGLE)
EFFECT_FLAG_DELAY				=0x10000	--Optional Trigger Effect cannot miss timing
EFFECT_FLAG_SINGLE_RANGE		=0x20000	--Sets the range of EFFECT_TYPE_SINGLE effects
EFFECT_FLAG_UNCOPYABLE			=0x40000	--Cannot be copied
EFFECT_FLAG_OATH				=0x80000	--(unused)
EFFECT_FLAG_SUMMON_PARAM		=0x100000	--Enables SetTargetRange to specify the summoning destination and position
EFFECT_FLAG_REPEAT				=0x200000	--(unused)
EFFECT_FLAG_NO_TURN_RESET		=0x400000	--"Once while face-up on the field"
EFFECT_FLAG_EVENT_PLAYER		=0x800000	--(unused)
EFFECT_FLAG_OWNER_RELATE		=0x1000000	--(unused)
EFFECT_FLAG_AVAILABLE_BD		=0x2000000	--(N/A)
EFFECT_FLAG_CLIENT_HINT			=0x4000000	--Enables a tooltip of the effect (can only be used outside initial_effect)
EFFECT_FLAG_CHAIN_UNIQUE		=0x8000000	--(N/A)
EFFECT_FLAG_LIMIT_ZONE			=0x10000000	--(unused, not available in YGOPro Percy)
EFFECT_FLAG_CHAIN_LIMIT			=0x20000000	--Cannot be Chained to
EFFECT_FLAG_CHARGE				=0x40000000	--Non-"Charge" spell that is put into the mana zone instead of the graveyard
EFFECT_FLAG_IMMEDIATELY_APPLY	=0x80000000	--(unused)

EFFECT_FLAG2_NAGA				=0x0001		--(N/A)
EFFECT_FLAG2_COF				=0x0002		--(unused)
EFFECT_FLAG2_MAJESTIC_MUST_COPY	=0x80000000	--(unused, only available in YGOPro Percy)
--Effect Code
EFFECT_IMMUNE_EFFECT				=1		--(unused)
EFFECT_DISABLE						=2		--(unused)
EFFECT_CANNOT_DISABLE				=3		--(unused)
EFFECT_SET_CONTROL					=4		--(unused)
EFFECT_CANNOT_CHANGE_CONTROL		=5		--(unused)
EFFECT_CANNOT_ACTIVATE				=6		--Player cannot activate effects
EFFECT_CANNOT_TRIGGER				=7		--Card cannot activate effects
EFFECT_DISABLE_EFFECT				=8		--(unused)
EFFECT_DISABLE_CHAIN				=9		--(unused)
EFFECT_DISABLE_TRAPMONSTER			=10		--(unused)
EFFECT_CANNOT_INACTIVATE			=12		--(unused)
EFFECT_CANNOT_DISEFFECT				=13		--(unused)
EFFECT_CANNOT_CHANGE_POSITION		=14		--Cannot change position
EFFECT_TRAP_ACT_IN_HAND				=15		--(unused)
EFFECT_TRAP_ACT_IN_SET_TURN			=16		--(unused)
EFFECT_REMAIN_FIELD					=17		--(unused)
EFFECT_MONSTER_SSET					=18		--Monster can be Set in the Spell & Trap Zone
EFFECT_CANNOT_SUMMON				=20		--Cannot Normal Summon monsters
EFFECT_CANNOT_FLIP_SUMMON			=21		--(unused)
EFFECT_CANNOT_SUMMON_CREATURE		=22		--Cannot summon creatures
EFFECT_CANNOT_MSET					=23		--Cannot Set monsters
EFFECT_CANNOT_SSET					=24		--Cannot Set Spells/Traps
EFFECT_CANNOT_DRAW					=25		--(unused)
EFFECT_CANNOT_DISABLE_SUMMON		=26		--(unused)
EFFECT_CANNOT_DISABLE_SPSUMMON		=27		--(unused)
EFFECT_SET_SUMMON_COUNT_LIMIT		=28		--(unused)
EFFECT_EXTRA_SUMMON_COUNT			=29		--(unused)
EFFECT_TO_BZONE_CONDITION			=30		--Condition to put a creature into the battle zone
EFFECT_REVIVE_LIMIT					=31		--(unused)
EFFECT_SUMMON_PROC					=32		--(unused)
EFFECT_LIMIT_SUMMON_PROC			=33		--(unused)
EFFECT_SUMMON_CREATURE_PROC			=34		--Creature summoning procedure
EFFECT_EXTRA_SET_COUNT				=35		--(unused)
EFFECT_SET_PROC						=36		--(unused)
EFFECT_LIMIT_SET_PROC				=37		--(unused)
EFFECT_DEVINE_LIGHT					=38		--(unused)
EFFECT_CANNOT_DISABLE_FLIP_SUMMON	=39		--(unused)
EFFECT_INDESTRUCTIBLE				=40		--Cannot be destroyed
EFFECT_INDESTRUCTIBLE_EFFECT		=41		--Cannot be destroyed by effects
EFFECT_INDESTRUCTIBLE_BATTLE		=42		--Cannot be destroyed by battle
EFFECT_UNRELEASABLE_SUM				=43		--(unused)
EFFECT_UNRELEASABLE_NONSUM			=44		--(unused)
EFFECT_DESTROY_SUBSTITUTE			=45		--(unused)
EFFECT_CANNOT_RELEASE				=46		--(unused)
EFFECT_INDESTRUCTIBLE_COUNT			=47		--(unused)
EFFECT_UNRELEASABLE_EFFECT			=48		--(unused)
EFFECT_DESTROY_REPLACE				=50		--Substitute a card being destroyed with another action
EFFECT_RELEASE_REPLACE				=51		--(unused)
EFFECT_SEND_REPLACE					=52		--Put a card into another location instead of X
EFFECT_CANNOT_DISCARD_HAND			=55		--(unused)
EFFECT_CANNOT_DISCARD_DECK			=56		--(unused)
EFFECT_CANNOT_USE_AS_COST			=57		--(unused)
EFFECT_CANNOT_PLACE_COUNTER			=58		--(unused)
EFFECT_CANNOT_TO_GRAVE_AS_COST		=59		--(unused)
EFFECT_LEAVE_FIELD_REDIRECT			=60		--(unused)
EFFECT_TO_HAND_REDIRECT				=61		--(unused)
EFFECT_TO_DECK_REDIRECT				=62		--(unused)
EFFECT_TO_MZONE_REDIRECT			=63		--Put a card into another location instead of the mana zone
EFFECT_TO_GRAVE_REDIRECT			=64		--Put a card into another location instead of the graveyard
EFFECT_CANNOT_TO_HAND				=65		--(unused)
EFFECT_CANNOT_TO_DECK				=66		--(unused)
EFFECT_CANNOT_TO_GRAVE				=67		--Cannot be put into the graveyard
EFFECT_CANNOT_TO_MZONE				=68		--Cannot be put into the mana zone
EFFECT_CANNOT_TURN_SET				=69		--(unused)
EFFECT_CANNOT_BE_BATTLE_TARGET		=70		--Cannot be targeted for attacks
EFFECT_CANNOT_BE_EFFECT_TARGET		=71		--Cannot be targeted by effects
EFFECT_IGNORE_BATTLE_TARGET			=72		--(unused)
EFFECT_CANNOT_ATTACK_PLAYER			=73		--Cannot attack player
EFFECT_ATTACK_PLAYER				=74		--Can attack player
EFFECT_DUAL_STATUS					=75		--(unused)
EFFECT_EQUIP_LIMIT					=76		--(unused)
EFFECT_DUAL_SUMMONABLE				=77		--(unused)
EFFECT_REVERSE_DAMAGE				=80		--(unused)
EFFECT_REVERSE_RECOVER				=81		--(unused)
EFFECT_CHANGE_DAMAGE				=82		--(unused)
EFFECT_REFLECT_DAMAGE				=83		--(unused)
EFFECT_CANNOT_ATTACK				=85		--Cannot attack
EFFECT_CANNOT_ATTACK_ANNOUNCE		=86		--(unused)
EFFECT_CANNOT_CHANGE_POS_E			=87		--Cannot change position by effects
EFFECT_ACTIVATE_COST				=90		--(unused)
EFFECT_SUMMON_COST					=91		--(unused)
EFFECT_SPSUMMON_COST				=92		--(unused)
EFFECT_FLIPSUMMON_COST				=93		--(unused)
EFFECT_MSET_COST					=94		--(unused)
EFFECT_SSET_COST					=95		--(unused)
EFFECT_ATTACK_COST					=96		--Add attack cost

EFFECT_UPDATE_POWER					=100	--Increase/decrease power
EFFECT_SET_POWER					=101	--Set power
EFFECT_SET_ATTACK_FINAL				=102	--(unused)
EFFECT_SET_BASE_ATTACK				=103	--(unused)
EFFECT_UPDATE_DEFENSE				=104	--(unused)
EFFECT_SET_DEFENSE					=105	--(unused)
EFFECT_SET_DEFENSE_FINAL			=106	--(unused)
EFFECT_SET_BASE_DEFENSE				=107	--Set original DEF
EFFECT_REVERSE_UPDATE				=108	--(unused)
EFFECT_SWAP_AD						=109	--(unused)
EFFECT_SWAP_BASE_AD					=110	--(unused)
EFFECT_SWAP_ATTACK_FINAL			=111	--(N/A)
EFFECT_SWAP_DEFENSE_FINAL			=112	--(N/A)
EFFECT_ADD_CODE						=113	--(unused)
EFFECT_CHANGE_CODE					=114	--Change card name
EFFECT_ADD_TYPE						=115	--(unused)
EFFECT_REMOVE_TYPE					=116	--(unused)
EFFECT_CHANGE_TYPE					=117	--Change card type
EFFECT_ADD_RACE						=120	--(unused)
EFFECT_REMOVE_RACE					=121	--(unused)
EFFECT_CHANGE_RACE					=122	--(unused)
EFFECT_ADD_CIVILIZATION				=125	--Add civilization
EFFECT_REMOVE_ATTRIBUTE				=126	--(unused)
EFFECT_CHANGE_CIVILIZATION			=127	--Change civilization
EFFECT_UPDATE_PLAY_COST				=130	--Increase/decrease the mana cost required for playing a card
EFFECT_CHANGE_MANA_COST				=131	--Set mana cost
EFFECT_UPDATE_RANK					=132	--(unused)
EFFECT_CHANGE_RANK					=133	--(unused)
EFFECT_UPDATE_LSCALE				=134	--(unused)
EFFECT_CHANGE_LSCALE				=135	--(unused)
EFFECT_UPDATE_RSCALE				=136	--(unused)
EFFECT_CHANGE_RSCALE				=137	--(unused)
EFFECT_SET_POSITION					=140	--(unused)
EFFECT_SELF_DESTROY					=141	--(unused)
EFFECT_SELF_TOGRAVE					=142	--(unused)
EFFECT_DOUBLE_TRIBUTE				=150	--(unused)
EFFECT_DECREASE_TRIBUTE				=151	--(unused)
EFFECT_DECREASE_TRIBUTE_SET			=152	--(unused)
EFFECT_EXTRA_RELEASE				=153	--(unused)
EFFECT_TRIBUTE_LIMIT				=154	--(unused)
EFFECT_EXTRA_RELEASE_SUM			=155	--(unused)
EFFECT_TRIPLE_TRIBUTE				=156	--(N/A)
EFFECT_ADD_EXTRA_TRIBUTE			=157	--(unused, not available in YGOPro Percy)
EFFECT_EXTRA_RELEASE_NONSUM			=158	--(unused, not available in YGOPro Percy)
EFFECT_PUBLIC						=160	--(unused)
EFFECT_COUNTER_PERMIT				=0x10000--(unused)
EFFECT_COUNTER_LIMIT				=0x20000--(unused)
EFFECT_RCOUNTER_REPLACE				=0x30000--(unused)
EFFECT_LPCOST_CHANGE				=170	--(unused)
EFFECT_LPCOST_REPLACE				=171	--(unused)
EFFECT_SKIP_DP						=180	--Skip Draw Phase
EFFECT_SKIP_SP						=181	--Skip Standby Phase
EFFECT_SKIP_M1						=182	--(unused) Skip Main Phase 1
EFFECT_SKIP_BP						=183	--(unused) Skip Battle Phase
EFFECT_SKIP_M2						=184	--(unused) Skip Main Phase 2
EFFECT_CANNOT_BP					=185	--(unused) Cannot conduct Battle Phase
EFFECT_CANNOT_M2					=186	--Cannot conduct Main Phase 2
EFFECT_CANNOT_EP					=187	--(unused) Cannot conduct End Phase
EFFECT_SKIP_TURN					=188	--Skip the entire turn
EFFECT_DEFENSE_ATTACK				=190	--(unused)
EFFECT_MUST_ATTACK					=191	--Must attack if able
EFFECT_FIRST_ATTACK					=192	--(unused)
EFFECT_ATTACK_ALL					=193	--(unused)
EFFECT_EXTRA_ATTACK					=194	--Increase the number of attacks
EFFECT_MUST_BE_ATTACKED				=195	--Must be attacked (only available in YGOPro Percy)
EFFECT_ONLY_BE_ATTACKED				=196	--(unused)
EFFECT_ATTACK_DISABLED				=197	--(unused)
EFFECT_NO_BATTLE_DAMAGE				=200	--(unused)
EFFECT_AVOID_BATTLE_DAMAGE			=201	--Take no battle damage from attacks involving this card
EFFECT_REFLECT_BATTLE_DAMAGE		=202	--(unused)
EFFECT_PIERCE						=203	--(unused)
EFFECT_BATTLE_DESTROY_REDIRECT		=204	--(unused)
EFFECT_BATTLE_DAMAGE_TO_EFFECT		=205	--(unused)
EFFECT_BOTH_BATTLE_DAMAGE			=206	--(unused, not available in YGOPro Percy)
EFFECT_ALSO_BATTLE_DAMAGE			=207	--(unused, not available in YGOPro Percy)
EFFECT_CHANGE_BATTLE_DAMAGE			=208	--(unused, not available in YGOPro Percy)
EFFECT_TOSS_COIN_REPLACE			=220	--(unused)
EFFECT_TOSS_DICE_REPLACE			=221	--(unused)
EFFECT_FUSION_MATERIAL				=230	--(unused)
EFFECT_CHAIN_MATERIAL				=231	--(unused)
EFFECT_SYNCHRO_MATERIAL				=232	--(unused)
EFFECT_XYZ_MATERIAL					=233	--(unused)
EFFECT_FUSION_SUBSTITUTE			=234	--(unused)
EFFECT_CANNOT_BE_FUSION_MATERIAL	=235	--(unused)
EFFECT_CANNOT_BE_SYNCHRO_MATERIAL	=236	--(unused)
EFFECT_SYNCHRO_MATERIAL_CUSTOM		=237	--(unused)
EFFECT_CANNOT_BE_XYZ_MATERIAL		=238	--(unused)
EFFECT_CANNOT_BE_LINK_MATERIAL		=239	--(unused)
EFFECT_SYNCHRO_LEVEL				=240	--(unused)
EFFECT_RITUAL_LEVEL					=241	--(unused)
EFFECT_XYZ_LEVEL					=242	--(unused)
EFFECT_EXTRA_RITUAL_MATERIAL		=243	--(unused)
EFFECT_NONTUNER						=244	--(unused)
EFFECT_OVERLAY_REMOVE_REPLACE		=245	--(unused)
EFFECT_SCRAP_CHIMERA				=246	--(unused)
EFFECT_TUNE_MAGICIAN_X				=247	--(unused)
EFFECT_TUNE_MAGICIAN_F				=248	--(unused, not available in YGOPro Percy)
EFFECT_PRE_MONSTER					=250	--(unused)
EFFECT_MATERIAL_CHECK				=251	--(unused)
EFFECT_DISABLE_FIELD				=260	--(unused)
EFFECT_USE_EXTRA_MZONE				=261	--(unused)
EFFECT_USE_EXTRA_SZONE				=262	--(unused)
EFFECT_MAX_MZONE					=263	--(unused)
EFFECT_MAX_SZONE					=264	--(unused)
EFFECT_FORCE_MZONE					=265	--(unused, only available in YGOPro Percy)
EFFECT_BECOME_LINKED_ZONE			=266	--(unused, only available in YGOPro Percy)
EFFECT_HAND_LIMIT					=270	--Change the hand size limit
EFFECT_DRAW_COUNT					=271	--(unused)
EFFECT_SPIRIT_DONOT_RETURN			=280	--(unused)
EFFECT_SPIRIT_MAYNOT_RETURN			=281	--(unused)
EFFECT_CHANGE_ENVIRONMENT			=290	--(unused)
EFFECT_NECRO_VALLEY					=291	--(unused)
EFFECT_FORBIDDEN					=292	--(unused)
EFFECT_NECRO_VALLEY_IM				=293	--(unused)
EFFECT_REVERSE_DECK					=294	--(unused)
EFFECT_REMOVE_BRAINWASHING			=295	--(unused)
EFFECT_BP_TWICE						=296	--(unused)
EFFECT_UNIQUE_CHECK					=297	--(unused)
EFFECT_MATCH_KILL					=300	--(unused)
EFFECT_SYNCHRO_CHECK				=310	--(unused)
EFFECT_QP_ACT_IN_NTPHAND			=311	--(unused)
EFFECT_MUST_BE_MATERIAL				=312	--(unused, only available in YGOPro Percy)
EFFECT_TO_GRAVE_REDIRECT_CB			=313	--(unused)
EFFECT_CHANGE_LEVEL_FINAL			=314	--(unused, only available in YGOPro Percy)
EFFECT_CHANGE_RANK_FINAL			=315	--(unused, only available in YGOPro Percy)
EFFECT_MUST_BE_FMATERIAL			=316	--(unused, only available in YGOPro Percy)
EFFECT_MUST_BE_XMATERIAL			=317	--(unused, only available in YGOPro Percy)
EFFECT_MUST_BE_LMATERIAL			=318	--(unused, only available in YGOPro Percy)
EFFECT_SPSUMMON_PROC_G				=320	--(unused)
EFFECT_SPSUMMON_COUNT_LIMIT			=330	--(unused)
EFFECT_LEFT_SPSUMMON_COUNT			=331	--(unused)
EFFECT_CANNOT_SELECT_BATTLE_TARGET	=332	--Cannot target cards for attacks
EFFECT_CANNOT_SELECT_EFFECT_TARGET	=333	--(unused)
EFFECT_ADD_SETCODE					=334	--Add setname
EFFECT_ADD_CREATURE_RACE			=334	--Add race
EFFECT_ADD_CREATURE_RACE_CATEGORY	=334	--Add race category
EFFECT_NO_EFFECT_DAMAGE				=335	--(unused)
EFFECT_UNSUMMONABLE_CARD			=336	--(unused, only available in YGOPro Percy)
EFFECT_DISABLE_CHAIN_FIELD			=337	--(N/A)
EFFECT_DISCARD_COST_CHANGE			=338	--(unused)
EFFECT_HAND_SYNCHRO					=339	--(unused)
EFFECT_ADD_FUSION_CODE				=340	--(unused)
EFFECT_ADD_FUSION_SETCODE			=341	--(unused)
EFFECT_RISE_TO_FULL_HEIGHT			=342	--(unused, only available in YGOPro Percy)
EFFECT_ONLY_ATTACK_MONSTER			=343	--(unused)
EFFECT_MUST_ATTACK_CREATURE			=344	--Must attack X if able
EFFECT_PATRICIAN_OF_DARKNESS		=345	--(unused)
EFFECT_EXTRA_ATTACK_MONSTER			=346	--(unused)
EFFECT_UNION_STATUS					=347	--(unused)
EFFECT_OLDUNION_STATUS				=348	--(unused)
EFFECT_ADD_FUSION_ATTRIBUTE			=349	--(unused, reserved)
EFFECT_REMOVE_FUSION_ATTRIBUTE		=350	--(unused, reserved)
EFFECT_CHANGE_FUSION_ATTRIBUTE		=351	--(unused)
EFFECT_EXTRA_FUSION_MATERIAL		=352	--(unused)
EFFECT_TUNER_MATERIAL_LIMIT			=353	--(unused)
EFFECT_ADD_LINK_CODE				=354	--(unused)
EFFECT_ADD_LINK_SETCODE				=355	--(unused, reserved)
EFFECT_ADD_LINK_ATTRIBUTE			=356	--(unused, not available in YGOPro Percy)
EFFECT_ADD_LINK_RACE				=357	--(unused, not available in YGOPro Percy)
EFFECT_EXTRA_MATERIAL				=358	--(unused, only available in YGOPro Percy)
EFFECT_QP_ACT_IN_SET_TURN			=359	--(unused, not available in YGOPro Percy)
EFFECT_EXTRA_PENDULUM_SUMMON		=360	--(unused, not available in YGOPro Percy)
EFFECT_MATERIAL_LIMIT				=361	--(unused, not available in YGOPro Percy)
EFFECT_SET_BATTLE_ATTACK			=362	--(unused, not available in YGOPro Percy)
EFFECT_SET_BATTLE_DEFENSE			=363	--(unused, not available in YGOPro Percy)
--The following is only available in YGOPro Percy
EFFECT_CANNOT_LOSE_DECK				=400	--(unused)
EFFECT_CANNOT_LOSE_LP				=401	--(unused)
EFFECT_CANNOT_LOSE_EFFECT			=402	--(unused)
EFFECT_BP_FIRST_TURN				=403	--Can conduct the Battle Phase of the first turn
EFFECT_UNSTOPPABLE_ATTACK			=404	--(unused)
EFFECT_ALLOW_NEGATIVE				=405	--(unused)
EFFECT_SELF_ATTACK					=406	--(unused)
EFFECT_BECOME_QUICK					=407	--(unused)
EFFECT_LEVEL_RANK					=408	--(unused)
EFFECT_RANK_LEVEL					=409	--(unused)
EFFECT_LEVEL_RANK_S					=410	--(unused)
EFFECT_RANK_LEVEL_S					=411	--(unused)
EFFECT_UPDATE_LINK					=420	--(unused)
EFFECT_CHANGE_LINK					=421	--(unused)
EFFECT_CHANGE_LINK_FINAL			=422	--(unused)
EFFECT_ADD_LINKMARKER				=423	--(unused)
EFFECT_REMOVE_LINKMARKER			=424	--(unused)
EFFECT_CHANGE_LINKMARKER			=425	--(unused)
--The following is only available in YGOPro DM
EFFECT_IGNORE_TAP					=500	--Workaround to not tap a creature at the end of the Damage Step
EFFECT_BROKEN_SHIELD				=501	--Register a broken shield
EFFECT_BLOCKED						=502	--Register a creature that has become blocked
EFFECT_BREAK_SHIELD					=503	--Register number of broken shields
EFFECT_BLOCKER						=600	--Blocker ("Dia Nork, Moonlight Guardian" DM-01 2/110)
EFFECT_SHIELD_TRIGGER				=601	--Shield Trigger ("Holy Awe" DM-01 6/110)
EFFECT_SLAYER						=602	--Slayer ("Bone Assassin, the Ripper" DM-01 47/110)
EFFECT_BREAKER						=603	--Breaker ("Gigaberos" DM-01 55/110)
EFFECT_DOUBLE_BREAKER				=604	--Double Breaker ("Gigaberos" DM-01 55/110)
EFFECT_POWER_ATTACKER				=605	--Power Attacker ("Brawler Zyler" DM-01 70/110)
EFFECT_UNTAPPED_BE_ATTACKED			=606	--Can be attacked as though it were tapped ("Chaos Strike" DM-01 72/110)
EFFECT_ATTACK_UNTAPPED				=607	--Can attack untapped creatures ("Gatling Skyterror" DM-01 79/110)
EFFECT_CANNOT_ATTACK_CREATURE		=608	--Cannot attack creatures ("Diamond Cutter" DM-02 1/55)
EFFECT_IGNORE_SUMMONING_SICKNESS	=609	--Ignore summoning sickness ("Diamond Cutter" DM-02 1/55)
EFFECT_IGNORE_CANNOT_ATTACK			=610	--Ignore "This creature can't attack" ("Diamond Cutter" DM-02 1/55)
EFFECT_IGNORE_CANNOT_ATTACK_PLAYER	=611	--Ignore "This creature can't attack players" ("Diamond Cutter" DM-02 1/55)
EFFECT_TRIPLE_BREAKER				=612	--Triple Breaker ("Bolgash Dragon" DM-05 37/55)
EFFECT_SPEED_ATTACKER				=613	--Speed Attacker ("Bombat, General of Speed" DM-05 38/55)
EFFECT_ENTER_BZONE_TAPPED			=614	--Creature is put into the battle zone tapped ("Lu Gila, Silver Rift Guardian" DM-06 2/110)
EFFECT_NO_BLOCK_BATTLE				=615	--No battle happens when a creature blocks ("Chekicul, Vizier of Endurance" DM-06 15/110)
EFFECT_CHANGE_SHIELD_BREAK_PLAYER	=616	--You choose the shield to break when an opponent's creature would break a shield ("Kyuroro" DM-06 36/110)
EFFECT_NO_BE_BLOCKED_BATTLE			=617	--No battle happens when a creature becomes blocked ("Badlands Lizard" DM-06 74/110)
EFFECT_CREW_BREAKER					=618	--Crew Breaker ("Q-tronic Gargantua" DM-06 86/110)
EFFECT_EVOLUTION_ANY_RACE			=619	--Can put an evolution creature of any race on a creature with this ability ("Innocent Hunter, Blade of All" DM-06 103/110)
EFFECT_BREAK_SHIELD_REPLACE			=620	--When a creature would break a shield, do something else to that shield instead ("Bolmeteus Steel Dragon" DM-06 S7/S10)
EFFECT_STEALTH						=621	--Stealth ("Kizar Basiku, the Outrageous" DM-07 9/55)
EFFECT_CHARGER						=622	--Charger ("Lightning Charger" DM-07 15/55)
EFFECT_DONOT_DISCARD_SHIELD_TRIGGER	=623	--Do not discard a spell after using its "Shield Trigger" ability ("Super Terradragon Bailas Gale" DM-08 S5/S5)
EFFECT_MUST_BLOCK					=624	--Creature must block another creature if able ("Storm Wrangler, the Furious" DM-09 51/55)
EFFECT_SILENT_SKILL					=625	--Keep creature tapped during Untap Step to use its "Silent Skill" ability ("Kejila, the Hidden Horror" DM-10 5/110)
EFFECT_PLAYER_CANNOT_UNTAP_START	=626	--Player cannot untap cards in their mana zone at the start of each of their turns ("Terradragon Cusdalf" DM-10 93/110)
EFFECT_WAVE_STRIKER					=627	--Wave Striker ("Asra, Vizier of Safety" DM-11 6/55)
EFFECT_DONOT_UNTAP_START_STEP		=628	--Does not untap at the start of the turn ("Warped Lunatron" DM-11 23/55)
EFFECT_CANNOT_USE_TAP_ABILITY		=629	--Player cannot use the Tap ability of their creatures ("Lockdown Lizard" DM-11 39/55)
EFFECT_VORTEX_EVOLUTION				=630	--Vortex Evolution ("Soul Phoenix, Avatar of Unity" DM-12 5/55)
EFFECT_EVOLUTION_SOURCE_REMAIN		=631	--When an evolution creature would leave the battle zone, only the top card leaves instead ("Soul Phoenix, Avatar of Unity" DM-12 5/55)
EFFECT_CHANGE_SHIELD_CHOOSE_PLAYER	=632	--When your opponent would choose your shield, you choose instead ("Meloppe" DM-12 9/55)
EFFECT_BREAK_EXTRA_SHIELD			=633	--Breaks one more shield ("Dyno Mantis, the Mightspinner" L10 Y2)
EFFECT_SYMPATHY						=634	--Sympathy ("Akashic First, Electro-Dragon" DM-13 3/55)
EFFECT_CONFIRM_BROKEN_SHIELD		=635	--Player reveals their shields broken by their opponent's creatures ("Rubels, the Explorer" DM-13 36/55)
EFFECT_CHARGE_TAPPED				=636	--Put a cast spell with this ability into the mana zone tapped instead of the graveyard ("Pixie Cocoon" DM-13 50/55)
EFFECT_WINS_ALL_BATTLES				=699	--Wins All Battles ("Marshias, Spirit of the Sun" DM-14 S1/S10)
--Event Code
--Events that can be used as a trigger for Trigger Effects
EVENT_STARTUP					=1000	--(unused)
EVENT_FLIP						=1001	--(unused)
EVENT_FREE_CHAIN				=1002	--Open window to activate Ignition and Trigger Effects
EVENT_DESTROY					=1010	--(unused)
EVENT_TO_GRAVE					=1011	--When a card is put into the graveyard
EVENT_TO_HAND					=1012	--(reserved) When a card is put into the hand
EVENT_TO_DECK					=1013	--(reserved) When a card is put into the deck
EVENT_TO_MZONE					=1014	--(reserved) When a card is put into the mana zone
EVENT_LEAVE_BZONE				=1015	--When a creature leaves the battle zone (excluding being added to the shield zone)
EVENT_CHANGE_POS				=1016	--When a card position is changed
EVENT_RELEASE					=1017	--(unused)
EVENT_DISCARD					=1018	--When a card is discarded from the hand
EVENT_LEAVE_FIELD_P				=1019	--(unused)
EVENT_CHAIN_SOLVING				=1020	--(unused)
EVENT_CHAIN_ACTIVATING			=1021	--(unused)
EVENT_CHAIN_SOLVED				=1022	--After a Chain resolves
EVENT_CHAIN_ACTIVATED			=1023	--(N/A)
EVENT_CHAIN_NEGATED				=1024	--(unused)
EVENT_CHAIN_DISABLED			=1025	--(unused)
EVENT_CHAIN_END					=1026	--When a series of Chains has resolved
EVENT_CHAINING					=1027	--When a card/effect is activating in response to another card/effect
EVENT_BECOME_TARGET				=1028	--(unused)
EVENT_DESTROYED					=1029	--When a creature is destroyed
EVENT_MOVE						=1030	--(unused, not available in YGOPro Percy)
EVENT_ADJUST					=1040	--After adjusting the adjust_all() card
EVENT_BREAK_EFFECT				=1050	--(unused, not available in YGOPro Percy)
EVENT_SUMMON_SUCCESS			=1100	--(unused)
EVENT_FLIP_SUMMON_SUCCESS		=1101	--(unused)
EVENT_COME_INTO_PLAY			=1102	--When a creature is put into the battle zone
EVENT_SUMMON					=1103	--(unused)
EVENT_FLIP_SUMMON				=1104	--(unused)
EVENT_SPSUMMON					=1105	--(unused)
EVENT_MSET						=1106	--(unused)
EVENT_SSET						=1107	--(unused)
EVENT_BE_MATERIAL				=1108	--(unused)
EVENT_BE_PRE_MATERIAL			=1109	--(unused)
EVENT_DRAW						=1110	--When a card is drawn
EVENT_DAMAGE					=1111	--(unused)
EVENT_RECOVER					=1112	--(unused)
EVENT_UNTAP_STEP				=1113	--Start of Turn Step (Untap Step)
EVENT_SUMMON_NEGATED			=1114	--(unused, not available in YGOPro Percy)
EVENT_FLIP_SUMMON_NEGATED		=1115	--(unused, not available in YGOPro Percy)
EVENT_SPSUMMON_NEGATED			=1116	--(unused, not available in YGOPro Percy)
EVENT_CONTROL_CHANGED			=1120	--(unused)
EVENT_EQUIP						=1121	--(unused)
EVENT_ATTACK_ANNOUNCE			=1130	--When a card declares an attack
EVENT_BE_BATTLE_TARGET			=1131	--When a card is targeted for an attack
EVENT_BATTLE_START				=1132	--(unused)
EVENT_BATTLE_CONFIRM			=1133	--When a creature is attacking and is not blocked
EVENT_ATTACK_SHIELD				=1134	--Before an attacking creature breaks the opponent's shield
EVENT_DAMAGE_CALCULATING		=1135	--(N/A)
EVENT_PRE_BATTLE_DAMAGE			=1136	--When battle damage occurs (using EFFECT_TYPE_CONTINUOUS)
EVENT_BATTLE_END				=1137	--(N/A)
EVENT_BATTLED					=1138	--At the end of a battle
EVENT_BATTLE_DESTROYING			=1139	--When a creature wins a battle
EVENT_BATTLE_DESTROYED			=1140	--(unused)
EVENT_ATTACK_END				=1141	--At the end of an attack
EVENT_ATTACK_DISABLED			=1142	--(unused)
EVENT_BATTLE_DAMAGE				=1143	--(unused)
EVENT_TOSS_DICE					=1150	--(unused)
EVENT_TOSS_COIN					=1151	--(unused)
EVENT_TOSS_COIN_NEGATE			=1152	--(unused)
EVENT_TOSS_DICE_NEGATE			=1153	--(unused)
EVENT_LEVEL_UP					=1200	--(unused)
EVENT_PAY_LPCOST				=1201	--(unused)
EVENT_DETACH_MATERIAL			=1202	--(unused)
EVENT_RETURN_TO_GRAVE			=1203	--(unused)
EVENT_TURN_END					=1210	--At the end of the turn
EVENT_PHASE						=0x1000	--During a phase of a turn (combined with PHASE constant)
EVENT_PHASE_START				=0x2000	--At the start of a phase of a turn (combined with PHASE constant)
EVENT_ADD_COUNTER				=0x10000	--(unused, combined with counter ID)
EVENT_REMOVE_COUNTER			=0x20000	--(unused, combined with counter ID)
EVENT_CUSTOM					=0x10000000	--Custom event
--The following is only available in YGOPro DM
EVENT_BECOME_SHIELD_TRIGGER		=CARD_WOLFIS_BLUE_DIVINE_DRAGON	--Card gets "Shield Trigger" (Can be summoned or cast for no cost)
EVENT_TRIGGER_SHIELD_TRIGGER	=CARD_HOLY_AWE					--Trigger a card's "Shield Trigger" ability
EVENT_WIN_BATTLE				=CARD_BLOODY_SQUITO				--When a creature wins a battle (used with EVENT_BATTLE_DESTROYING)
EVENT_BECOME_BLOCKED			=CARD_CREEPING_PLAGUE			--When a creature becomes blocked
EVENT_BLOCK						=CARD_SPIRAL_GRASS				--When a creature blocks
EVENT_ATTACK_PLAYER				=CARD_MARROW_OOZE_THE_TWISTER	--When a creature attacks a player
EVENT_BREAK_SHIELD				=CARD_BRUTAL_CHARGE				--When a creature finishes attacking the opponent and broke a shield
EVENT_EVOLUTION_TO_BZONE		=CARD_KACHUA_KEEPER				--When an evolution creature is put into the battle zone by effect
EVENT_TRIGGER_BLOCKER			=CARD_STORM_WRANGLER_THE_FURIOUS--Trigger a creature's "Blocker" ability
EVENT_CAST_FREE					=CARD_BLUUM_ERKIS_FLARE_GUARDIAN--Cast a spell immediately for no cost
EVENT_UNTAP_START_STEP			=CARD_WARPED_LUNATRON			--When a card untaps during Start of Turn Step
EVENT_TO_SZONE					=CARD_SOUL_PHOENIX				--When a card is added to a player's shields
EVENT_LOSE_BATTLE				=CARD_GASHI_GASHI				--When a creature loses a battle (used with EVENT_BATTLED)
--Effect Category
CATEGORY_BLOCKER				=0x1	--Blocker ("Laser Wing" DM-01 11/110)
CATEGORY_SHIELD_TRIGGER			=0x2	--Shield Trigger ("Fu Reil, Seeker of Storms" DM-04 8/55)
--Hint
--Message displayed in the center of the screen
HINT_EVENT				=1	--(unused)
HINT_MESSAGE			=2	--Display a string
HINT_SELECTMSG			=3	--Display a selection message
HINT_OPSELECTED			=4	--Display the selected effect
HINT_EFFECT				=5	--(unused)
HINT_RACE				=6	--(unused)
HINT_ATTRIB				=7	--(unused)
HINT_CODE				=8	--(unused)
HINT_NUMBER				=9	--Display the numerical value selected by the effect
HINT_CARD				=10	--Display the card name selected by the effect
HINT_ZONE				=11	--(unused, not available in YGOPro Percy)
--Card Hint
--Message displayed in the white frame that appears when you place the cursor on the card
CHINT_TURN				=1	--(unused)
CHINT_CARD				=2	--(unused)
CHINT_RACE				=3	--(unused)
CHINT_ATTRIBUTE			=4	--(unused)
CHINT_NUMBER			=5	--(unused)
CHINT_DESC				=6	--(unused)
--Opcode
OPCODE_ADD				=0x40000000		--(unused)
OPCODE_SUB				=0x40000001		--(unused)
OPCODE_MUL				=0x40000002		--(unused)
OPCODE_DIV				=0x40000003		--(unused)
OPCODE_AND				=0x40000004		--(unused)
OPCODE_OR				=0x40000005		--(unused)
OPCODE_NEG				=0x40000006		--(unused)
OPCODE_NOT				=0x40000007		--(unused)
OPCODE_ISCODE			=0x40000100		--(unused)
OPCODE_ISSETCARD		=0x40000101		--(unused)
OPCODE_ISTYPE			=0x40000102		--(unused)
OPCODE_ISRACE			=0x40000103		--(unused)
OPCODE_ISATTRIBUTE		=0x40000104		--(unused)
--Damage
DOUBLE_DAMAGE			=0x80000000		--(unused, not available in YGOPro Percy)
HALF_DAMAGE				=0x80000001		--(unused, not available in YGOPro Percy)
--Hint Message
--Message displayed at the top of the screen
HINTMSG_TOMZONE			=500	--Choose a card to put into the mana zone.
HINTMSG_TAP				=501	--Choose a card to tap.
HINTMSG_BREAK			=502	--Choose a shield to break.
HINTMSG_ANNOUNCECHOOSE	=503	--Choose how many cards?
HINTMSG_TARGET			=504	--Choose a target for the ability.
HINTMSG_RTOHAND			=505	--Choose a card to return to its owner's hand.
HINTMSG_ATOHAND			=506	--Choose a card to put into your hand.
HINTMSG_UNTAP			=507	--Choose a card to untap.
HINTMSG_DESTROY			=508	--Choose a card to destroy.
HINTMSG_DISCARD			=509	--Choose a card to discard.
HINTMSG_TOGRAVE			=510	--Choose a card to put into the graveyard.
HINTMSG_CREATURE		=511	--Choose a creature.
HINTMSG_EVOLVE			=512	--Choose a creature to evolve.
HINTMSG_CONFIRM			=513	--Choose a card to look at it.
HINTMSG_TODECK			=514	--Choose a card to return to its owner's deck.
HINTMSG_TOSZONE			=515	--Choose a card to add to its owner's shields.
HINTMSG_TOBZONE			=516	--Choose a creature to put into the battle zone.
HINTMSG_ANNOUNCETOSZONE	=517	--Add how many to shields?
HINTMSG_ANNOUNCERACE	=518	--Choose a race.
HINTMSG_ANNOUNCECIV		=519	--Choose a civilization(s).
HINTMSG_ANNOUNCEDRAW	=520	--Draw how many cards?
HINTMSG_ANNOUNCECOST	=521	--Choose a mana cost.
HINTMSG_ANNOUNCEPOWER	=522	--Choose a power.
HINTMSG_ANNOUNCENAME	=523	--Name a card.
HINTMSG_ATTACKTARGET	=549	--Choose a creature to attack.
HINTMSG_APPLYABILITY	=556	--Choose an ability to apply.
--Information displayed in a dialog box
ERROR_DECKCOUNT			=1450	--Your deck must be exactly 40 cards!
ERROR_NOBZONES			=1630	--You may have up to 5 creatures in the battle zone when playing with this app. However, there is no limit when playing the actual card game.
ERROR_NOSZONES			=1631	--You may have up to 5 shields when playing with this app. However, there is no limit when playing the actual card game.
ERROR_NOTARGETS			=1632	--There is no applicable card.
ERROR_NOSTRIGGER		=1633	--There is no "Shield Trigger" ability that can be activated during this time.
--Yes No Message (for Duel.SelectYesNo)
YESNOMSG_CHOOSE			=600	--Choose a card?
YESNOMSG_TOSZONE		=601	--Add a card to your shields?
YESNOMSG_TOHAND			=602	--Put a card into its owner's hand?
YESNOMSG_UNTAP			=603	--Untap a card?
YESNOMSG_DRAW			=604	--Draw a card?
--Option (for Duel.SelectOption)
OPTION_HEADS			=60		--(unused)
OPTION_TAILS			=61		--(unused)
OPTION_LIGHT_BRINGER	=700	--Light Bringer
OPTION_GUARDIAN			=701	--Guardian
OPTION_STARLIGHT_TREE	=702	--Starlight Tree
OPTION_INITIATE			=703	--Initiate
OPTION_BERSERKER		=704	--Berserker
OPTION_LIQUID_PEOPLE	=705	--Liquid People
OPTION_CYBER_VIRUS		=706	--Cyber Virus
OPTION_FISH				=707	--Fish
OPTION_GEL_FISH			=708	--Gel Fish
OPTION_LEVIATHAN		=709	--Leviathan
OPTION_CYBER_LORD		=710	--Cyber Lord
OPTION_GHOST			=711	--Ghost
OPTION_BRAIN_JACKER		=712	--Brain Jacker
OPTION_LIVING_DEAD		=713	--Living Dead
OPTION_CHIMERA			=714	--Chimera
OPTION_PARASITE_WORM	=715	--Parasite Worm
OPTION_DARK_LORD		=716	--Dark Lord
OPTION_ARMORLOID		=717	--Armorloid
OPTION_MACHINE_EATER	=718	--Machine Eater
OPTION_ARMORED_DRAGON	=719	--Armored Dragon
OPTION_HUMAN			=720	--Human
OPTION_DRAGO_NOID		=721	--Dragonoid
OPTION_ARMORED_WYVERN	=722	--Armored Wyvern
OPTION_ROCK_BEAST		=723	--Rock Beast
OPTION_BEAST_FOLK		=724	--Beast Folk
OPTION_TREE_FOLK		=725	--Tree Folk
OPTION_COLONY_BEETLE	=726	--Colony Beetle
OPTION_GIANT_INSECT		=727	--Giant Insect
OPTION_BALLOON_MUSHROOM	=728	--Balloon Mushroom
OPTION_HORNED_BEAST		=729	--Horned Beast
OPTION_ANGEL_COMMAND	=730	--Angel Command
OPTION_DEMON_COMMAND	=731	--Demon Command
OPTION_MECHA_THUNDER	=732	--Mecha Thunder
OPTION_CYBER_CLUSTER	=733	--Cyber Cluster
OPTION_HEDRIAN			=734	--Hedrian
OPTION_FIRE_BIRD		=735	--Fire Bird
OPTION_GIANT			=736	--Giant
OPTION_SURVIVOR			=737	--Survivor
OPTION_SEA_HACKER		=738	--Sea Hacker
OPTION_RAINBOW_PHANTOM	=739	--Rainbow Phantom
OPTION_GLADIATOR		=740	--Gladiator
OPTION_EARTH_EATER		=741	--Earth Eater
OPTION_DEVIL_MASK		=742	--Devil Mask
OPTION_DEATH_PUPPET		=743	--Death Puppet
OPTION_DUNE_GECKO		=744	--Dune Gecko
OPTION_XENOPARTS		=745	--Xenoparts
OPTION_MYSTERY_TOTEM	=746	--Mystery Totem
OPTION_SNOW_FAERIE		=747	--Snow Faerie
OPTION_VOLCANO_DRAGON	=748	--Volcano Dragon
OPTION_MECHA_DEL_SOL	=749	--Mecha Del Sol
OPTION_ZOMBIE_DRAGON	=750	--Zombie Dragon
OPTION_EARTH_DRAGON		=751	--Earth Dragon
OPTION_SOLTROOPER		=752	--Soltrooper
OPTION_CYBER_MOON		=753	--Cyber Moon
OPTION_MERFOLK			=754	--Merfolk
OPTION_PANDORAS_BOX		=755	--Pandora's Box
OPTION_MELT_WARRIOR		=756	--Melt Warrior
OPTION_WILD_VEGGIES		=757	--Wild Veggies
OPTION_SPIRIT_QUARTZ	=758	--Spirit Quartz
OPTION_PHOENIX			=759	--Phoenix
OPTION_STARNOID			=760	--Starnoid
OPTION_NAGA				=761	--Naga
OPTION_PEGASUS			=762	--Pegasus
--Description (for SetDescription, EFFECT_FLAG_CLIENT_HINT)
DESC_BROKEN				=300	--Broken shield
DESC_SUMMONSICKNESS		=301	--Summoning Sickness
DESC_CANNOTATTACK		=302	--Can't attack
DESC_SUMMON				=1152	--Summon
DESC_EVOLVE				=1170	--Evolve
DESC_UNTAP_STEP			=1650	--Untap your creatures in the battle zone and cards in your mana zone.
DESC_CHARGE_STEP		=1651	--You may put a card into your mana zone.
DESC_LOSE_BATTLE		=1652	--Destroy the creature(s) that lost the battle.
DESC_BLOCKED			=1653	--Your creature has been blocked!
DESC_BLOCKER			=1660	--Blocker (Whenever an opponent's creature attacks, you may tap this creature to stop the attack. Then the 2 creatures battle.)
DESC_SHIELD_TRIGGER_S	=1661	--(reserved) Shield Trigger (When this spell is put into your hand from your shield zone, you may cast it immediately for no cost.)
DESC_SLAYER				=1662	--Slayer (Whenever this creature battles, destroy the other creature after the battle.)
DESC_SHIELD_TRIGGER_C	=1663	--Shield Trigger (When this creature is put into your hand from your shield zone, you may summon it immediately for no cost.)
DESC_FN_BLOCKER			=1664	--Fire and nature blocker (Whenever an opponent's fire or nature creature attacks, you may tap this creature to stop the attack. Then the 2 creatures battle.)
DESC_NL_SLAYER			=1665	--Nature and light slayer (Whenever this creature battles a nature or light creature, destroy the other creature after the battle.)
DESC_SHIELD_SAVER		=1666	--Shield Saver (When one of your shields would be broken, you may destroy this creature instead.)
DESC_TURBO_RUSH			=1667	--Turbo rush (If any of your other creatures broke any shields this turn, this creature gets its Turborush ability until the end of the turn.)
DESC_DRAGON_BLOCKER		=1668	--Dragon blocker (Whenever an opponent's creature that has Dragon in its race attacks, you may tap this creature to stop the attack. Then the 2 creatures battle.)
DESC_DARKNESS_BLOCKER	=1669	--Darkness blocker (Whenever an opponent's darkness creature attacks, you may tap this creature to stop the attack. Then the 2 creatures battle.)
DESC_LIGHT_BLOCKER		=1670	--Light blocker (Whenever an opponent's light creature attacks, you may tap this creature to stop the attack. Then the 2 creatures battle.)
DESC_NON_BREAKER		=1800	--(reserved) This creature breaks 1 shield.
DESC_DOUBLE_BREAKER		=1801	--Double Breaker (This creature breaks 2 shields.)
DESC_TRIPLE_BREAKER		=1802	--Triple Breaker (This creature breaks 3 shields.)
DESC_CREW_BREAKER		=1803	--Crew Breaker—"RACE" (This creature breaks one more shield for each of your other "RACE" in the battle zone.)
--Timing
--Free Chain activation timing
TIMING_DRAW_PHASE			=0x1			--(unused)
TIMING_STANDBY_PHASE		=0x2			--(unused)
TIMING_MAIN_END				=0x4			--(unused)
TIMING_BATTLE_START			=0x8			--Start of Battle Phase
TIMING_BATTLE_END			=0x10			--End of Battle Phase
TIMING_END_PHASE			=0x20			--(unused)
TIMING_SUMMON				=0x40			--(unused)
TIMING_SPSUMMON				=0x80			--(unused)
TIMING_FLIPSUMMON			=0x100			--(unused)
TIMING_MSET					=0x200			--(unused)
TIMING_SSET					=0x400			--(unused)
TIMING_POS_CHANGE			=0x800			--(unused)
TIMING_ATTACK				=0x1000			--(unused)
TIMING_DAMAGE_STEP			=0x2000			--(unused)
TIMING_DAMAGE_CAL			=0x4000			--(unused)
TIMING_CHAIN_END			=0x8000			--(unused)
TIMING_DRAW					=0x10000		--(unused)
TIMING_DAMAGE				=0x20000		--(unused)
TIMING_RECOVER				=0x40000		--(unused)
TIMING_DESTROY				=0x80000		--(unused)
TIMING_REMOVE				=0x100000		--(unused)
TIMING_TOHAND				=0x200000		--(unused)
TIMING_TODECK				=0x400000		--(unused)
TIMING_TOGRAVE				=0x800000		--(unused)
TIMING_BATTLE_PHASE			=0x1000000		--Battle Phase
TIMING_EQUIP				=0x2000000		--(unused)
TIMING_BATTLE_STEP_END		=0x4000000		--End of Battle Step
TIMING_ATTACK_STEP			=TIMING_BATTLE_START+TIMING_BATTLE_END+TIMING_BATTLE_PHASE+TIMING_BATTLE_STEP_END	--Attack Step
--Timing combinations
TIMINGS_CHECK_MONSTER		=0x1c0			--(unused) TIMING_SUMMON+TIMING_SPSUMMON+TIMING_FLIPSUMMON
--Global Flag
--Special effect flag
GLOBALFLAG_DECK_REVERSE_CHECK	=0x1		--(unused)
GLOBALFLAG_BRAINWASHING_CHECK	=0x2		--(unused)
GLOBALFLAG_SCRAP_CHIMERA		=0x4		--(unused)
GLOBALFLAG_DELAYED_QUICKEFFECT	=0x8		--(N/A)
GLOBALFLAG_DETACH_EVENT			=0x10		--(unused)
GLOBALFLAG_MUST_BE_SMATERIAL	=0x20		--(unused)
GLOBALFLAG_SPSUMMON_COUNT		=0x40		--(unused)
GLOBALFLAG_XMAT_COUNT_LIMIT		=0x80		--(unused)
GLOBALFLAG_SELF_TOGRAVE			=0x100		--(unused)
GLOBALFLAG_SPSUMMON_ONCE		=0x200		--(unused)
GLOBALFLAG_TUNE_MAGICIAN		=0x400		--(unused)
--Effect Count Code
--Limit the number of effects that can be used
EFFECT_COUNT_CODE_OATH			=0x10000000	--(unused)
EFFECT_COUNT_CODE_DUEL			=0x20000000	--(unused)
EFFECT_COUNT_CODE_SINGLE		=0x1		--(unused)
--Duel Options
DUEL_TEST_MODE			=0x01	--Test mode (not currently available)
DUEL_ATTACK_FIRST_TURN	=0x02	--Can attack during the first turn (for puzzles)
DUEL_NO_CHAIN_HINT		=0x04	--(N/A)
DUEL_OBSOLETE_RULING	=0x08	--Use old rules
DUEL_PSEUDO_SHUFFLE		=0x10	--Do not shuffle Deck
DUEL_TAG_MODE			=0x20	--2v2
DUEL_SIMPLE_AI			=0x40	--Semi-automatic AI (for puzzles)
SPEED_DUEL				=0x80	--Speed Duel (only available in YGOPro Percy)
--Activity Counter
--global: 1-6 (binary: 5,6)
--custom: 1-5,7 (binary: 1-5)
ACTIVITY_SUMMON			=1		--(unused)
ACTIVITY_NORMALSUMMON	=2		--(unused)
ACTIVITY_SPSUMMON		=3		--(unused)
ACTIVITY_FLIPSUMMON		=4		--(unused)
ACTIVITY_ATTACK			=5		--(unused)
ACTIVITY_BATTLE_PHASE	=6		--(unused, not available in Duel.AddCustomActivityCounter)
ACTIVITY_CHAIN			=7		--Check if a card or effect was activated (only available in Duel.AddCustomActivityCounter)
--Announce Type
ANNOUNCE_CARD			=0x7	--(unused, only available in YGOPro Percy)
ANNOUNCE_CARD_FILTER	=0x8	--(unused, only available in YGOPro Percy)
